/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AthleteProfileRequest from './models/AthleteProfileRequest';
import AthleteProfileResponse from './models/AthleteProfileResponse';
import AthleteRegisterRequest from './models/AthleteRegisterRequest';
import AthleteTeamResponse from './models/AthleteTeamResponse';
import AuthChangePasswordPostRequest from './models/AuthChangePasswordPostRequest';
import BiometricInput from './models/BiometricInput';
import ErrorResponse from './models/ErrorResponse';
import InviteAllResponse from './models/InviteAllResponse';
import InviteCancelRequest from './models/InviteCancelRequest';
import InviteCreateRequest from './models/InviteCreateRequest';
import InviteCreateResponse from './models/InviteCreateResponse';
import InviteDetailsRequest from './models/InviteDetailsRequest';
import InviteDetailsResponse from './models/InviteDetailsResponse';
import InviteRegisterRequest from './models/InviteRegisterRequest';
import LoginRequest from './models/LoginRequest';
import LoginResponse from './models/LoginResponse';
import TeamsJoinPostRequest from './models/TeamsJoinPostRequest';
import TrainingPlansItemsItemIdOverridePostRequest from './models/TrainingPlansItemsItemIdOverridePostRequest';
import TrainingPlansPlanIdAssignPostRequest from './models/TrainingPlansPlanIdAssignPostRequest';
import TrainingPlansPlanIdItemsPostRequest from './models/TrainingPlansPlanIdItemsPostRequest';
import TrainingPlansPostRequest from './models/TrainingPlansPostRequest';
import AuthApi from './api/AuthApi';
import BiometricsApi from './api/BiometricsApi';
import TeamsApi from './api/TeamsApi';
import TrainingApi from './api/TrainingApi';


/**
* Система для регистрации, авторизации и управления ролями пользователей. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Api = require('index'); // See note below*.
* var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AthleteProfileRequest model constructor.
     * @property {module:models/AthleteProfileRequest}
     */
    AthleteProfileRequest,

    /**
     * The AthleteProfileResponse model constructor.
     * @property {module:models/AthleteProfileResponse}
     */
    AthleteProfileResponse,

    /**
     * The AthleteRegisterRequest model constructor.
     * @property {module:models/AthleteRegisterRequest}
     */
    AthleteRegisterRequest,

    /**
     * The AthleteTeamResponse model constructor.
     * @property {module:models/AthleteTeamResponse}
     */
    AthleteTeamResponse,

    /**
     * The AuthChangePasswordPostRequest model constructor.
     * @property {module:models/AuthChangePasswordPostRequest}
     */
    AuthChangePasswordPostRequest,

    /**
     * The BiometricInput model constructor.
     * @property {module:models/BiometricInput}
     */
    BiometricInput,

    /**
     * The ErrorResponse model constructor.
     * @property {module:models/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The InviteAllResponse model constructor.
     * @property {module:models/InviteAllResponse}
     */
    InviteAllResponse,

    /**
     * The InviteCancelRequest model constructor.
     * @property {module:models/InviteCancelRequest}
     */
    InviteCancelRequest,

    /**
     * The InviteCreateRequest model constructor.
     * @property {module:models/InviteCreateRequest}
     */
    InviteCreateRequest,

    /**
     * The InviteCreateResponse model constructor.
     * @property {module:models/InviteCreateResponse}
     */
    InviteCreateResponse,

    /**
     * The InviteDetailsRequest model constructor.
     * @property {module:models/InviteDetailsRequest}
     */
    InviteDetailsRequest,

    /**
     * The InviteDetailsResponse model constructor.
     * @property {module:models/InviteDetailsResponse}
     */
    InviteDetailsResponse,

    /**
     * The InviteRegisterRequest model constructor.
     * @property {module:models/InviteRegisterRequest}
     */
    InviteRegisterRequest,

    /**
     * The LoginRequest model constructor.
     * @property {module:models/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginResponse model constructor.
     * @property {module:models/LoginResponse}
     */
    LoginResponse,

    /**
     * The TeamsJoinPostRequest model constructor.
     * @property {module:models/TeamsJoinPostRequest}
     */
    TeamsJoinPostRequest,

    /**
     * The TrainingPlansItemsItemIdOverridePostRequest model constructor.
     * @property {module:models/TrainingPlansItemsItemIdOverridePostRequest}
     */
    TrainingPlansItemsItemIdOverridePostRequest,

    /**
     * The TrainingPlansPlanIdAssignPostRequest model constructor.
     * @property {module:models/TrainingPlansPlanIdAssignPostRequest}
     */
    TrainingPlansPlanIdAssignPostRequest,

    /**
     * The TrainingPlansPlanIdItemsPostRequest model constructor.
     * @property {module:models/TrainingPlansPlanIdItemsPostRequest}
     */
    TrainingPlansPlanIdItemsPostRequest,

    /**
     * The TrainingPlansPostRequest model constructor.
     * @property {module:models/TrainingPlansPostRequest}
     */
    TrainingPlansPostRequest,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BiometricsApi service constructor.
    * @property {module:api/BiometricsApi}
    */
    BiometricsApi,

    /**
    * The TeamsApi service constructor.
    * @property {module:api/TeamsApi}
    */
    TeamsApi,

    /**
    * The TrainingApi service constructor.
    * @property {module:api/TrainingApi}
    */
    TrainingApi
};
