/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AllAthletesResponse from './models/AllAthletesResponse';
import AthleteIndicatorResponse from './models/AthleteIndicatorResponse';
import AthleteProfileRequest from './models/AthleteProfileRequest';
import AthleteProfileResponse from './models/AthleteProfileResponse';
import AthleteRegisterRequest from './models/AthleteRegisterRequest';
import AthleteTeamResponse from './models/AthleteTeamResponse';
import AuthChangePasswordPostRequest from './models/AuthChangePasswordPostRequest';
import BiometricInput from './models/BiometricInput';
import CoachProfileResponse from './models/CoachProfileResponse';
import CriticalAthleteProfileResponse from './models/CriticalAthleteProfileResponse';
import CriticalAthleteRequest from './models/CriticalAthleteRequest';
import CriticalAthleteResponse from './models/CriticalAthleteResponse';
import CriticalAthletesResponse from './models/CriticalAthletesResponse';
import ErrorResponse from './models/ErrorResponse';
import IndicatorLimit from './models/IndicatorLimit';
import InviteAllResponse from './models/InviteAllResponse';
import InviteCancelRequest from './models/InviteCancelRequest';
import InviteCreateRequest from './models/InviteCreateRequest';
import InviteCreateResponse from './models/InviteCreateResponse';
import InviteDetailsRequest from './models/InviteDetailsRequest';
import InviteDetailsResponse from './models/InviteDetailsResponse';
import InviteRegisterRequest from './models/InviteRegisterRequest';
import LoginRequest from './models/LoginRequest';
import LoginResponse from './models/LoginResponse';
import MedicalAssigment from './models/MedicalAssigment';
import MedicalstaffProfileResponse from './models/MedicalstaffProfileResponse';
import ReferAthlete from './models/ReferAthlete';
import ReferAthletesToMedicalstaffRequest from './models/ReferAthletesToMedicalstaffRequest';
import Team from './models/Team';
import TeamAthleteStatusResponse from './models/TeamAthleteStatusResponse';
import TeamCreateRequest from './models/TeamCreateRequest';
import TeamGetAthletesResponse from './models/TeamGetAthletesResponse';
import TeamGetCoachesResponse from './models/TeamGetCoachesResponse';
import TeamGetMedicalAssignmentsResponse from './models/TeamGetMedicalAssignmentsResponse';
import TeamGetMedicalstaffResponse from './models/TeamGetMedicalstaffResponse';
import TeamJoin from './models/TeamJoin';
import TeamJoinRequest from './models/TeamJoinRequest';
import TeamJoinsListResponse from './models/TeamJoinsListResponse';
import TeamRequest from './models/TeamRequest';
import TeamResponse from './models/TeamResponse';
import TrainingPlan from './models/TrainingPlan';
import TrainingPlanCreate from './models/TrainingPlanCreate';
import TrainingPlanItemCreate from './models/TrainingPlanItemCreate';
import TrainingPlanListResponse from './models/TrainingPlanListResponse';
import TrainingPlansItemsItemIdOverridePostRequest from './models/TrainingPlansItemsItemIdOverridePostRequest';
import TrainingPlansPlanIdAssignPostRequest from './models/TrainingPlansPlanIdAssignPostRequest';
import AuthApi from './api/AuthApi';
import BiometricsApi from './api/BiometricsApi';
import TeamsApi from './api/TeamsApi';
import TrainingApi from './api/TrainingApi';


/**
* Система для регистрации, авторизации и управления ролями пользователей. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Api = require('index'); // See note below*.
* var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AllAthletesResponse model constructor.
     * @property {module:models/AllAthletesResponse}
     */
    AllAthletesResponse,

    /**
     * The AthleteIndicatorResponse model constructor.
     * @property {module:models/AthleteIndicatorResponse}
     */
    AthleteIndicatorResponse,

    /**
     * The AthleteProfileRequest model constructor.
     * @property {module:models/AthleteProfileRequest}
     */
    AthleteProfileRequest,

    /**
     * The AthleteProfileResponse model constructor.
     * @property {module:models/AthleteProfileResponse}
     */
    AthleteProfileResponse,

    /**
     * The AthleteRegisterRequest model constructor.
     * @property {module:models/AthleteRegisterRequest}
     */
    AthleteRegisterRequest,

    /**
     * The AthleteTeamResponse model constructor.
     * @property {module:models/AthleteTeamResponse}
     */
    AthleteTeamResponse,

    /**
     * The AuthChangePasswordPostRequest model constructor.
     * @property {module:models/AuthChangePasswordPostRequest}
     */
    AuthChangePasswordPostRequest,

    /**
     * The BiometricInput model constructor.
     * @property {module:models/BiometricInput}
     */
    BiometricInput,

    /**
     * The CoachProfileResponse model constructor.
     * @property {module:models/CoachProfileResponse}
     */
    CoachProfileResponse,

    /**
     * The CriticalAthleteProfileResponse model constructor.
     * @property {module:models/CriticalAthleteProfileResponse}
     */
    CriticalAthleteProfileResponse,

    /**
     * The CriticalAthleteRequest model constructor.
     * @property {module:models/CriticalAthleteRequest}
     */
    CriticalAthleteRequest,

    /**
     * The CriticalAthleteResponse model constructor.
     * @property {module:models/CriticalAthleteResponse}
     */
    CriticalAthleteResponse,

    /**
     * The CriticalAthletesResponse model constructor.
     * @property {module:models/CriticalAthletesResponse}
     */
    CriticalAthletesResponse,

    /**
     * The ErrorResponse model constructor.
     * @property {module:models/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The IndicatorLimit model constructor.
     * @property {module:models/IndicatorLimit}
     */
    IndicatorLimit,

    /**
     * The InviteAllResponse model constructor.
     * @property {module:models/InviteAllResponse}
     */
    InviteAllResponse,

    /**
     * The InviteCancelRequest model constructor.
     * @property {module:models/InviteCancelRequest}
     */
    InviteCancelRequest,

    /**
     * The InviteCreateRequest model constructor.
     * @property {module:models/InviteCreateRequest}
     */
    InviteCreateRequest,

    /**
     * The InviteCreateResponse model constructor.
     * @property {module:models/InviteCreateResponse}
     */
    InviteCreateResponse,

    /**
     * The InviteDetailsRequest model constructor.
     * @property {module:models/InviteDetailsRequest}
     */
    InviteDetailsRequest,

    /**
     * The InviteDetailsResponse model constructor.
     * @property {module:models/InviteDetailsResponse}
     */
    InviteDetailsResponse,

    /**
     * The InviteRegisterRequest model constructor.
     * @property {module:models/InviteRegisterRequest}
     */
    InviteRegisterRequest,

    /**
     * The LoginRequest model constructor.
     * @property {module:models/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginResponse model constructor.
     * @property {module:models/LoginResponse}
     */
    LoginResponse,

    /**
     * The MedicalAssigment model constructor.
     * @property {module:models/MedicalAssigment}
     */
    MedicalAssigment,

    /**
     * The MedicalstaffProfileResponse model constructor.
     * @property {module:models/MedicalstaffProfileResponse}
     */
    MedicalstaffProfileResponse,

    /**
     * The ReferAthlete model constructor.
     * @property {module:models/ReferAthlete}
     */
    ReferAthlete,

    /**
     * The ReferAthletesToMedicalstaffRequest model constructor.
     * @property {module:models/ReferAthletesToMedicalstaffRequest}
     */
    ReferAthletesToMedicalstaffRequest,

    /**
     * The Team model constructor.
     * @property {module:models/Team}
     */
    Team,

    /**
     * The TeamAthleteStatusResponse model constructor.
     * @property {module:models/TeamAthleteStatusResponse}
     */
    TeamAthleteStatusResponse,

    /**
     * The TeamCreateRequest model constructor.
     * @property {module:models/TeamCreateRequest}
     */
    TeamCreateRequest,

    /**
     * The TeamGetAthletesResponse model constructor.
     * @property {module:models/TeamGetAthletesResponse}
     */
    TeamGetAthletesResponse,

    /**
     * The TeamGetCoachesResponse model constructor.
     * @property {module:models/TeamGetCoachesResponse}
     */
    TeamGetCoachesResponse,

    /**
     * The TeamGetMedicalAssignmentsResponse model constructor.
     * @property {module:models/TeamGetMedicalAssignmentsResponse}
     */
    TeamGetMedicalAssignmentsResponse,

    /**
     * The TeamGetMedicalstaffResponse model constructor.
     * @property {module:models/TeamGetMedicalstaffResponse}
     */
    TeamGetMedicalstaffResponse,

    /**
     * The TeamJoin model constructor.
     * @property {module:models/TeamJoin}
     */
    TeamJoin,

    /**
     * The TeamJoinRequest model constructor.
     * @property {module:models/TeamJoinRequest}
     */
    TeamJoinRequest,

    /**
     * The TeamJoinsListResponse model constructor.
     * @property {module:models/TeamJoinsListResponse}
     */
    TeamJoinsListResponse,

    /**
     * The TeamRequest model constructor.
     * @property {module:models/TeamRequest}
     */
    TeamRequest,

    /**
     * The TeamResponse model constructor.
     * @property {module:models/TeamResponse}
     */
    TeamResponse,

    /**
     * The TrainingPlan model constructor.
     * @property {module:models/TrainingPlan}
     */
    TrainingPlan,

    /**
     * The TrainingPlanCreate model constructor.
     * @property {module:models/TrainingPlanCreate}
     */
    TrainingPlanCreate,

    /**
     * The TrainingPlanItemCreate model constructor.
     * @property {module:models/TrainingPlanItemCreate}
     */
    TrainingPlanItemCreate,

    /**
     * The TrainingPlanListResponse model constructor.
     * @property {module:models/TrainingPlanListResponse}
     */
    TrainingPlanListResponse,

    /**
     * The TrainingPlansItemsItemIdOverridePostRequest model constructor.
     * @property {module:models/TrainingPlansItemsItemIdOverridePostRequest}
     */
    TrainingPlansItemsItemIdOverridePostRequest,

    /**
     * The TrainingPlansPlanIdAssignPostRequest model constructor.
     * @property {module:models/TrainingPlansPlanIdAssignPostRequest}
     */
    TrainingPlansPlanIdAssignPostRequest,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BiometricsApi service constructor.
    * @property {module:api/BiometricsApi}
    */
    BiometricsApi,

    /**
    * The TeamsApi service constructor.
    * @property {module:api/TeamsApi}
    */
    TeamsApi,

    /**
    * The TrainingApi service constructor.
    * @property {module:api/TrainingApi}
    */
    TrainingApi
};
