/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AthleteIndicatorResponse model module.
 * @module models/AthleteIndicatorResponse
 * @version 1.0.0
 */
class AthleteIndicatorResponse {
    /**
     * Constructs a new <code>AthleteIndicatorResponse</code>.
     * @alias module:models/AthleteIndicatorResponse
     */
    constructor() { 
        
        AthleteIndicatorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AthleteIndicatorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AthleteIndicatorResponse} obj Optional instance to populate.
     * @return {module:models/AthleteIndicatorResponse} The populated <code>AthleteIndicatorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AthleteIndicatorResponse();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('hrv')) {
                obj['hrv'] = ApiClient.convertToType(data['hrv'], 'Number');
            }
            if (data.hasOwnProperty('morning_pulse')) {
                obj['morning_pulse'] = ApiClient.convertToType(data['morning_pulse'], 'Number');
            }
            if (data.hasOwnProperty('evening_pulse')) {
                obj['evening_pulse'] = ApiClient.convertToType(data['evening_pulse'], 'Number');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AthleteIndicatorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AthleteIndicatorResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }

        return true;
    }


}



/**
 * @member {String} date
 */
AthleteIndicatorResponse.prototype['date'] = undefined;

/**
 * @member {Number} hrv
 */
AthleteIndicatorResponse.prototype['hrv'] = undefined;

/**
 * @member {Number} morning_pulse
 */
AthleteIndicatorResponse.prototype['morning_pulse'] = undefined;

/**
 * @member {Number} evening_pulse
 */
AthleteIndicatorResponse.prototype['evening_pulse'] = undefined;

/**
 * @member {Number} weight
 */
AthleteIndicatorResponse.prototype['weight'] = undefined;






export default AthleteIndicatorResponse;

