/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AthleteRegisterRequest model module.
 * @module models/AthleteRegisterRequest
 * @version 1.0.0
 */
class AthleteRegisterRequest {
    /**
     * Constructs a new <code>AthleteRegisterRequest</code>.
     * @alias module:models/AthleteRegisterRequest
     * @param email {String} 
     * @param password {String} 
     * @param firstName {String} 
     * @param lastName {String} 
     * @param middleName {String} 
     * @param gender {module:models/AthleteRegisterRequest.GenderEnum} 
     * @param dateOfBirth {Date} 
     */
    constructor(email, password, firstName, lastName, middleName, gender, dateOfBirth) { 
        
        AthleteRegisterRequest.initialize(this, email, password, firstName, lastName, middleName, gender, dateOfBirth);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password, firstName, lastName, middleName, gender, dateOfBirth) { 
        obj['email'] = email;
        obj['password'] = password;
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['middle_name'] = middleName;
        obj['gender'] = gender;
        obj['date_of_birth'] = dateOfBirth;
    }

    /**
     * Constructs a <code>AthleteRegisterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AthleteRegisterRequest} obj Optional instance to populate.
     * @return {module:models/AthleteRegisterRequest} The populated <code>AthleteRegisterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AthleteRegisterRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('date_of_birth')) {
                obj['date_of_birth'] = ApiClient.convertToType(data['date_of_birth'], 'Date');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AthleteRegisterRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AthleteRegisterRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AthleteRegisterRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['gender'] && !(typeof data['gender'] === 'string' || data['gender'] instanceof String)) {
            throw new Error("Expected the field `gender` to be a primitive type in the JSON string but got " + data['gender']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}

AthleteRegisterRequest.RequiredProperties = ["email", "password", "first_name", "last_name", "middle_name", "gender", "date_of_birth"];

/**
 * @member {String} email
 */
AthleteRegisterRequest.prototype['email'] = undefined;

/**
 * @member {String} password
 */
AthleteRegisterRequest.prototype['password'] = undefined;

/**
 * @member {String} first_name
 */
AthleteRegisterRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
AthleteRegisterRequest.prototype['last_name'] = undefined;

/**
 * @member {String} middle_name
 */
AthleteRegisterRequest.prototype['middle_name'] = undefined;

/**
 * @member {module:models/AthleteRegisterRequest.GenderEnum} gender
 */
AthleteRegisterRequest.prototype['gender'] = undefined;

/**
 * @member {Date} date_of_birth
 */
AthleteRegisterRequest.prototype['date_of_birth'] = undefined;

/**
 * @member {String} phone
 */
AthleteRegisterRequest.prototype['phone'] = undefined;





/**
 * Allowed values for the <code>gender</code> property.
 * @enum {String}
 * @readonly
 */
AthleteRegisterRequest['GenderEnum'] = {

    /**
     * value: "M"
     * @const
     */
    "M": "M",

    /**
     * value: "F"
     * @const
     */
    "F": "F"
};



export default AthleteRegisterRequest;

