/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AthleteTeamResponse model module.
 * @module models/AthleteTeamResponse
 * @version 1.0.0
 */
class AthleteTeamResponse {
    /**
     * Constructs a new <code>AthleteTeamResponse</code>.
     * @alias module:models/AthleteTeamResponse
     */
    constructor() { 
        
        AthleteTeamResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AthleteTeamResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AthleteTeamResponse} obj Optional instance to populate.
     * @return {module:models/AthleteTeamResponse} The populated <code>AthleteTeamResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AthleteTeamResponse();

            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('sport_type')) {
                obj['sport_type'] = ApiClient.convertToType(data['sport_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AthleteTeamResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AthleteTeamResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['team_name'] && !(typeof data['team_name'] === 'string' || data['team_name'] instanceof String)) {
            throw new Error("Expected the field `team_name` to be a primitive type in the JSON string but got " + data['team_name']);
        }
        // ensure the json data is a string
        if (data['sport_type'] && !(typeof data['sport_type'] === 'string' || data['sport_type'] instanceof String)) {
            throw new Error("Expected the field `sport_type` to be a primitive type in the JSON string but got " + data['sport_type']);
        }

        return true;
    }


}



/**
 * @member {String} team_name
 */
AthleteTeamResponse.prototype['team_name'] = undefined;

/**
 * @member {String} sport_type
 */
AthleteTeamResponse.prototype['sport_type'] = undefined;






export default AthleteTeamResponse;

