/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthChangePasswordPostRequest model module.
 * @module models/AuthChangePasswordPostRequest
 * @version 1.0.0
 */
class AuthChangePasswordPostRequest {
    /**
     * Constructs a new <code>AuthChangePasswordPostRequest</code>.
     * @alias module:models/AuthChangePasswordPostRequest
     * @param oldPassword {String} 
     * @param newPassword {String} 
     */
    constructor(oldPassword, newPassword) { 
        
        AuthChangePasswordPostRequest.initialize(this, oldPassword, newPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, oldPassword, newPassword) { 
        obj['old_password'] = oldPassword;
        obj['new_password'] = newPassword;
    }

    /**
     * Constructs a <code>AuthChangePasswordPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/AuthChangePasswordPostRequest} obj Optional instance to populate.
     * @return {module:models/AuthChangePasswordPostRequest} The populated <code>AuthChangePasswordPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthChangePasswordPostRequest();

            if (data.hasOwnProperty('old_password')) {
                obj['old_password'] = ApiClient.convertToType(data['old_password'], 'String');
            }
            if (data.hasOwnProperty('new_password')) {
                obj['new_password'] = ApiClient.convertToType(data['new_password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthChangePasswordPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthChangePasswordPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthChangePasswordPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['old_password'] && !(typeof data['old_password'] === 'string' || data['old_password'] instanceof String)) {
            throw new Error("Expected the field `old_password` to be a primitive type in the JSON string but got " + data['old_password']);
        }
        // ensure the json data is a string
        if (data['new_password'] && !(typeof data['new_password'] === 'string' || data['new_password'] instanceof String)) {
            throw new Error("Expected the field `new_password` to be a primitive type in the JSON string but got " + data['new_password']);
        }

        return true;
    }


}

AuthChangePasswordPostRequest.RequiredProperties = ["old_password", "new_password"];

/**
 * @member {String} old_password
 */
AuthChangePasswordPostRequest.prototype['old_password'] = undefined;

/**
 * @member {String} new_password
 */
AuthChangePasswordPostRequest.prototype['new_password'] = undefined;






export default AuthChangePasswordPostRequest;

