/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BiometricInput model module.
 * @module models/BiometricInput
 * @version 1.0.0
 */
class BiometricInput {
    /**
     * Constructs a new <code>BiometricInput</code>.
     * @alias module:models/BiometricInput
     * @param date {String} 
     * @param morningPulse {Number} 
     * @param eveningPulse {Number} 
     * @param HRV {Number} 
     * @param weight {Number} 
     */
    constructor(date, morningPulse, eveningPulse, HRV, weight) { 
        
        BiometricInput.initialize(this, date, morningPulse, eveningPulse, HRV, weight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, morningPulse, eveningPulse, HRV, weight) { 
        obj['date'] = date;
        obj['morning_pulse'] = morningPulse;
        obj['evening_pulse'] = eveningPulse;
        obj['HRV'] = HRV;
        obj['weight'] = weight;
    }

    /**
     * Constructs a <code>BiometricInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/BiometricInput} obj Optional instance to populate.
     * @return {module:models/BiometricInput} The populated <code>BiometricInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BiometricInput();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('morning_pulse')) {
                obj['morning_pulse'] = ApiClient.convertToType(data['morning_pulse'], 'Number');
            }
            if (data.hasOwnProperty('evening_pulse')) {
                obj['evening_pulse'] = ApiClient.convertToType(data['evening_pulse'], 'Number');
            }
            if (data.hasOwnProperty('HRV')) {
                obj['HRV'] = ApiClient.convertToType(data['HRV'], 'Number');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BiometricInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BiometricInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BiometricInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }

        return true;
    }


}

BiometricInput.RequiredProperties = ["date", "morning_pulse", "evening_pulse", "HRV", "weight"];

/**
 * @member {String} date
 */
BiometricInput.prototype['date'] = undefined;

/**
 * @member {Number} morning_pulse
 */
BiometricInput.prototype['morning_pulse'] = undefined;

/**
 * @member {Number} evening_pulse
 */
BiometricInput.prototype['evening_pulse'] = undefined;

/**
 * @member {Number} HRV
 */
BiometricInput.prototype['HRV'] = undefined;

/**
 * @member {Number} weight
 */
BiometricInput.prototype['weight'] = undefined;






export default BiometricInput;

