/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BiometricInput model module.
 * @module models/BiometricInput
 * @version 1.0.0
 */
class BiometricInput {
    /**
     * Constructs a new <code>BiometricInput</code>.
     * @alias module:models/BiometricInput
     * @param date {Date} 
     * @param timeOfDay {module:models/BiometricInput.TimeOfDayEnum} 
     */
    constructor(date, timeOfDay) { 
        
        BiometricInput.initialize(this, date, timeOfDay);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, timeOfDay) { 
        obj['date'] = date;
        obj['time_of_day'] = timeOfDay;
    }

    /**
     * Constructs a <code>BiometricInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/BiometricInput} obj Optional instance to populate.
     * @return {module:models/BiometricInput} The populated <code>BiometricInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BiometricInput();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('time_of_day')) {
                obj['time_of_day'] = ApiClient.convertToType(data['time_of_day'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
            if (data.hasOwnProperty('pulse')) {
                obj['pulse'] = ApiClient.convertToType(data['pulse'], 'Number');
            }
            if (data.hasOwnProperty('HRV')) {
                obj['HRV'] = ApiClient.convertToType(data['HRV'], 'Number');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BiometricInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BiometricInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BiometricInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['time_of_day'] && !(typeof data['time_of_day'] === 'string' || data['time_of_day'] instanceof String)) {
            throw new Error("Expected the field `time_of_day` to be a primitive type in the JSON string but got " + data['time_of_day']);
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }

        return true;
    }


}

BiometricInput.RequiredProperties = ["date", "time_of_day"];

/**
 * @member {Date} date
 */
BiometricInput.prototype['date'] = undefined;

/**
 * @member {module:models/BiometricInput.TimeOfDayEnum} time_of_day
 */
BiometricInput.prototype['time_of_day'] = undefined;

/**
 * @member {String} time
 */
BiometricInput.prototype['time'] = undefined;

/**
 * @member {Number} pulse
 */
BiometricInput.prototype['pulse'] = undefined;

/**
 * @member {Number} HRV
 */
BiometricInput.prototype['HRV'] = undefined;

/**
 * @member {Number} weight
 */
BiometricInput.prototype['weight'] = undefined;





/**
 * Allowed values for the <code>time_of_day</code> property.
 * @enum {String}
 * @readonly
 */
BiometricInput['TimeOfDayEnum'] = {

    /**
     * value: "morning"
     * @const
     */
    "morning": "morning",

    /**
     * value: "evening"
     * @const
     */
    "evening": "evening"
};



export default BiometricInput;

