/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachProfileResponse model module.
 * @module models/CoachProfileResponse
 * @version 1.0.0
 */
class CoachProfileResponse {
    /**
     * Constructs a new <code>CoachProfileResponse</code>.
     * @alias module:models/CoachProfileResponse
     * @param coachId {Number} 
     * @param firstName {String} 
     * @param lastName {String} 
     * @param middleName {String} 
     * @param email {String} 
     * @param phone {String} 
     */
    constructor(coachId, firstName, lastName, middleName, email, phone) { 
        
        CoachProfileResponse.initialize(this, coachId, firstName, lastName, middleName, email, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, coachId, firstName, lastName, middleName, email, phone) { 
        obj['coach_id'] = coachId;
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['middle_name'] = middleName;
        obj['email'] = email;
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>CoachProfileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CoachProfileResponse} obj Optional instance to populate.
     * @return {module:models/CoachProfileResponse} The populated <code>CoachProfileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachProfileResponse();

            if (data.hasOwnProperty('coach_id')) {
                obj['coach_id'] = ApiClient.convertToType(data['coach_id'], 'Number');
            }
            if (data.hasOwnProperty('role_in_team')) {
                obj['role_in_team'] = ApiClient.convertToType(data['role_in_team'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('license_number')) {
                obj['license_number'] = ApiClient.convertToType(data['license_number'], 'String');
            }
            if (data.hasOwnProperty('experience_level')) {
                obj['experience_level'] = ApiClient.convertToType(data['experience_level'], 'String');
            }
            if (data.hasOwnProperty('sport_type')) {
                obj['sport_type'] = ApiClient.convertToType(data['sport_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CoachProfileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CoachProfileResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CoachProfileResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['role_in_team'] && !(typeof data['role_in_team'] === 'string' || data['role_in_team'] instanceof String)) {
            throw new Error("Expected the field `role_in_team` to be a primitive type in the JSON string but got " + data['role_in_team']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['license_number'] && !(typeof data['license_number'] === 'string' || data['license_number'] instanceof String)) {
            throw new Error("Expected the field `license_number` to be a primitive type in the JSON string but got " + data['license_number']);
        }
        // ensure the json data is a string
        if (data['experience_level'] && !(typeof data['experience_level'] === 'string' || data['experience_level'] instanceof String)) {
            throw new Error("Expected the field `experience_level` to be a primitive type in the JSON string but got " + data['experience_level']);
        }
        // ensure the json data is a string
        if (data['sport_type'] && !(typeof data['sport_type'] === 'string' || data['sport_type'] instanceof String)) {
            throw new Error("Expected the field `sport_type` to be a primitive type in the JSON string but got " + data['sport_type']);
        }

        return true;
    }


}

CoachProfileResponse.RequiredProperties = ["coach_id", "first_name", "last_name", "middle_name", "email", "phone"];

/**
 * @member {Number} coach_id
 */
CoachProfileResponse.prototype['coach_id'] = undefined;

/**
 * @member {String} role_in_team
 */
CoachProfileResponse.prototype['role_in_team'] = undefined;

/**
 * @member {String} first_name
 */
CoachProfileResponse.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
CoachProfileResponse.prototype['last_name'] = undefined;

/**
 * @member {String} middle_name
 */
CoachProfileResponse.prototype['middle_name'] = undefined;

/**
 * @member {String} email
 */
CoachProfileResponse.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
CoachProfileResponse.prototype['phone'] = undefined;

/**
 * @member {String} license_number
 */
CoachProfileResponse.prototype['license_number'] = undefined;

/**
 * @member {String} experience_level
 */
CoachProfileResponse.prototype['experience_level'] = undefined;

/**
 * @member {String} sport_type
 */
CoachProfileResponse.prototype['sport_type'] = undefined;






export default CoachProfileResponse;

