/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CriticalAthleteProfileResponse from './CriticalAthleteProfileResponse';

/**
 * The CriticalAthletesResponse model module.
 * @module models/CriticalAthletesResponse
 * @version 1.0.0
 */
class CriticalAthletesResponse {
    /**
     * Constructs a new <code>CriticalAthletesResponse</code>.
     * @alias module:models/CriticalAthletesResponse
     */
    constructor() { 
        
        CriticalAthletesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CriticalAthletesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CriticalAthletesResponse} obj Optional instance to populate.
     * @return {module:models/CriticalAthletesResponse} The populated <code>CriticalAthletesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CriticalAthletesResponse();

            if (data.hasOwnProperty('athletes')) {
                obj['athletes'] = ApiClient.convertToType(data['athletes'], [CriticalAthleteProfileResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CriticalAthletesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CriticalAthletesResponse</code>.
     */
    static validateJSON(data) {
        if (data['athletes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['athletes'])) {
                throw new Error("Expected the field `athletes` to be an array in the JSON data but got " + data['athletes']);
            }
            // validate the optional field `athletes` (array)
            for (const item of data['athletes']) {
                CriticalAthleteProfileResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/CriticalAthleteProfileResponse>} athletes
 */
CriticalAthletesResponse.prototype['athletes'] = undefined;






export default CriticalAthletesResponse;

