/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AthleteIndicatorResponse from './AthleteIndicatorResponse';
import IndicatorLimit from './IndicatorLimit';

/**
 * The CriticalAthleteResponse model module.
 * @module models/CriticalAthleteResponse
 * @version 1.0.0
 */
class CriticalAthleteResponse {
    /**
     * Constructs a new <code>CriticalAthleteResponse</code>.
     * @alias module:models/CriticalAthleteResponse
     */
    constructor() { 
        
        CriticalAthleteResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CriticalAthleteResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CriticalAthleteResponse} obj Optional instance to populate.
     * @return {module:models/CriticalAthleteResponse} The populated <code>CriticalAthleteResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CriticalAthleteResponse();

            if (data.hasOwnProperty('period_type')) {
                obj['period_type'] = ApiClient.convertToType(data['period_type'], 'String');
            }
            if (data.hasOwnProperty('indicators')) {
                obj['indicators'] = ApiClient.convertToType(data['indicators'], [AthleteIndicatorResponse]);
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = ApiClient.convertToType(data['limits'], {'String': IndicatorLimit});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CriticalAthleteResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CriticalAthleteResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['period_type'] && !(typeof data['period_type'] === 'string' || data['period_type'] instanceof String)) {
            throw new Error("Expected the field `period_type` to be a primitive type in the JSON string but got " + data['period_type']);
        }
        if (data['indicators']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['indicators'])) {
                throw new Error("Expected the field `indicators` to be an array in the JSON data but got " + data['indicators']);
            }
            // validate the optional field `indicators` (array)
            for (const item of data['indicators']) {
                AthleteIndicatorResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} period_type
 */
CriticalAthleteResponse.prototype['period_type'] = undefined;

/**
 * @member {Array.<module:models/AthleteIndicatorResponse>} indicators
 */
CriticalAthleteResponse.prototype['indicators'] = undefined;

/**
 * @member {Object.<String, module:models/IndicatorLimit>} limits
 */
CriticalAthleteResponse.prototype['limits'] = undefined;






export default CriticalAthleteResponse;

