/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CriticalAthleteRequest model module.
 * @module models/CriticalAthleteRequest
 * @version 1.0.0
 */
class CriticalAthleteRequest {
    /**
     * Constructs a new <code>CriticalAthleteRequest</code>.
     * @alias module:models/CriticalAthleteRequest
     */
    constructor() { 
        
        CriticalAthleteRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CriticalAthleteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CriticalAthleteRequest} obj Optional instance to populate.
     * @return {module:models/CriticalAthleteRequest} The populated <code>CriticalAthleteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CriticalAthleteRequest();

            if (data.hasOwnProperty('athlete_id')) {
                obj['athlete_id'] = ApiClient.convertToType(data['athlete_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CriticalAthleteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CriticalAthleteRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} athlete_id
 */
CriticalAthleteRequest.prototype['athlete_id'] = undefined;






export default CriticalAthleteRequest;

