/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AthleteIndicatorResponse from './AthleteIndicatorResponse';
import IndicatorLimit from './IndicatorLimit';

/**
 * The CriticalAthleteProfileResponse model module.
 * @module models/CriticalAthleteProfileResponse
 * @version 1.0.0
 */
class CriticalAthleteProfileResponse {
    /**
     * Constructs a new <code>CriticalAthleteProfileResponse</code>.
     * @alias module:models/CriticalAthleteProfileResponse
     */
    constructor() { 
        
        CriticalAthleteProfileResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CriticalAthleteProfileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CriticalAthleteProfileResponse} obj Optional instance to populate.
     * @return {module:models/CriticalAthleteProfileResponse} The populated <code>CriticalAthleteProfileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CriticalAthleteProfileResponse();

            if (data.hasOwnProperty('athlete_id')) {
                obj['athlete_id'] = ApiClient.convertToType(data['athlete_id'], 'Number');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('period_type')) {
                obj['period_type'] = ApiClient.convertToType(data['period_type'], 'String');
            }
            if (data.hasOwnProperty('indicators')) {
                obj['indicators'] = ApiClient.convertToType(data['indicators'], [AthleteIndicatorResponse]);
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = ApiClient.convertToType(data['limits'], {'String': IndicatorLimit});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CriticalAthleteProfileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CriticalAthleteProfileResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['team_name'] && !(typeof data['team_name'] === 'string' || data['team_name'] instanceof String)) {
            throw new Error("Expected the field `team_name` to be a primitive type in the JSON string but got " + data['team_name']);
        }
        // ensure the json data is a string
        if (data['period_type'] && !(typeof data['period_type'] === 'string' || data['period_type'] instanceof String)) {
            throw new Error("Expected the field `period_type` to be a primitive type in the JSON string but got " + data['period_type']);
        }
        if (data['indicators']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['indicators'])) {
                throw new Error("Expected the field `indicators` to be an array in the JSON data but got " + data['indicators']);
            }
            // validate the optional field `indicators` (array)
            for (const item of data['indicators']) {
                AthleteIndicatorResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} athlete_id
 */
CriticalAthleteProfileResponse.prototype['athlete_id'] = undefined;

/**
 * @member {String} first_name
 */
CriticalAthleteProfileResponse.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
CriticalAthleteProfileResponse.prototype['last_name'] = undefined;

/**
 * @member {String} middle_name
 */
CriticalAthleteProfileResponse.prototype['middle_name'] = undefined;

/**
 * @member {String} team_name
 */
CriticalAthleteProfileResponse.prototype['team_name'] = undefined;

/**
 * @member {String} period_type
 */
CriticalAthleteProfileResponse.prototype['period_type'] = undefined;

/**
 * @member {Array.<module:models/AthleteIndicatorResponse>} indicators
 */
CriticalAthleteProfileResponse.prototype['indicators'] = undefined;

/**
 * @member {Object.<String, module:models/IndicatorLimit>} limits
 */
CriticalAthleteProfileResponse.prototype['limits'] = undefined;






export default CriticalAthleteProfileResponse;

