/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IndicatorLimit model module.
 * @module models/IndicatorLimit
 * @version 1.0.0
 */
class IndicatorLimit {
    /**
     * Constructs a new <code>IndicatorLimit</code>.
     * @alias module:models/IndicatorLimit
     */
    constructor() { 
        
        IndicatorLimit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IndicatorLimit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/IndicatorLimit} obj Optional instance to populate.
     * @return {module:models/IndicatorLimit} The populated <code>IndicatorLimit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IndicatorLimit();

            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IndicatorLimit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IndicatorLimit</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} min
 */
IndicatorLimit.prototype['min'] = undefined;

/**
 * @member {Number} max
 */
IndicatorLimit.prototype['max'] = undefined;






export default IndicatorLimit;

