/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InviteDetailsRequest model module.
 * @module models/InviteDetailsRequest
 * @version 1.0.0
 */
class InviteDetailsRequest {
    /**
     * Constructs a new <code>InviteDetailsRequest</code>.
     * @alias module:models/InviteDetailsRequest
     */
    constructor() { 
        
        InviteDetailsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InviteDetailsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InviteDetailsRequest} obj Optional instance to populate.
     * @return {module:models/InviteDetailsRequest} The populated <code>InviteDetailsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteDetailsRequest();

            if (data.hasOwnProperty('invite_code')) {
                obj['invite_code'] = ApiClient.convertToType(data['invite_code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteDetailsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteDetailsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['invite_code'] && !(typeof data['invite_code'] === 'string' || data['invite_code'] instanceof String)) {
            throw new Error("Expected the field `invite_code` to be a primitive type in the JSON string but got " + data['invite_code']);
        }

        return true;
    }


}



/**
 * @member {String} invite_code
 */
InviteDetailsRequest.prototype['invite_code'] = undefined;






export default InviteDetailsRequest;

