/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InviteDetailsResponse from './InviteDetailsResponse';

/**
 * The InviteAllResponse model module.
 * @module models/InviteAllResponse
 * @version 1.0.0
 */
class InviteAllResponse {
    /**
     * Constructs a new <code>InviteAllResponse</code>.
     * @alias module:models/InviteAllResponse
     */
    constructor() { 
        
        InviteAllResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InviteAllResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InviteAllResponse} obj Optional instance to populate.
     * @return {module:models/InviteAllResponse} The populated <code>InviteAllResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteAllResponse();

            if (data.hasOwnProperty('invites')) {
                obj['invites'] = ApiClient.convertToType(data['invites'], [InviteDetailsResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteAllResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteAllResponse</code>.
     */
    static validateJSON(data) {
        if (data['invites']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['invites'])) {
                throw new Error("Expected the field `invites` to be an array in the JSON data but got " + data['invites']);
            }
            // validate the optional field `invites` (array)
            for (const item of data['invites']) {
                InviteDetailsResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/InviteDetailsResponse>} invites
 */
InviteAllResponse.prototype['invites'] = undefined;






export default InviteAllResponse;

