/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InviteRegisterRequest model module.
 * @module models/InviteRegisterRequest
 * @version 1.0.0
 */
class InviteRegisterRequest {
    /**
     * Constructs a new <code>InviteRegisterRequest</code>.
     * @alias module:models/InviteRegisterRequest
     * @param inviteCode {String} 
     * @param email {String} 
     * @param password {String} 
     * @param role {module:models/InviteRegisterRequest.RoleEnum} 
     * @param firstName {String} 
     * @param lastName {String} 
     * @param middleName {String} 
     * @param licenseNumber {String} 
     */
    constructor(inviteCode, email, password, role, firstName, lastName, middleName, licenseNumber) { 
        
        InviteRegisterRequest.initialize(this, inviteCode, email, password, role, firstName, lastName, middleName, licenseNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, inviteCode, email, password, role, firstName, lastName, middleName, licenseNumber) { 
        obj['invite_code'] = inviteCode;
        obj['email'] = email;
        obj['password'] = password;
        obj['role'] = role;
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['middle_name'] = middleName;
        obj['license_number'] = licenseNumber;
    }

    /**
     * Constructs a <code>InviteRegisterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InviteRegisterRequest} obj Optional instance to populate.
     * @return {module:models/InviteRegisterRequest} The populated <code>InviteRegisterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteRegisterRequest();

            if (data.hasOwnProperty('invite_code')) {
                obj['invite_code'] = ApiClient.convertToType(data['invite_code'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('license_number')) {
                obj['license_number'] = ApiClient.convertToType(data['license_number'], 'String');
            }
            if (data.hasOwnProperty('organization_id')) {
                obj['organization_id'] = ApiClient.convertToType(data['organization_id'], 'Number');
            }
            if (data.hasOwnProperty('sport_type_id')) {
                obj['sport_type_id'] = ApiClient.convertToType(data['sport_type_id'], 'Number');
            }
            if (data.hasOwnProperty('specialization')) {
                obj['specialization'] = ApiClient.convertToType(data['specialization'], 'String');
            }
            if (data.hasOwnProperty('experience_level')) {
                obj['experience_level'] = ApiClient.convertToType(data['experience_level'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteRegisterRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteRegisterRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InviteRegisterRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['invite_code'] && !(typeof data['invite_code'] === 'string' || data['invite_code'] instanceof String)) {
            throw new Error("Expected the field `invite_code` to be a primitive type in the JSON string but got " + data['invite_code']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['license_number'] && !(typeof data['license_number'] === 'string' || data['license_number'] instanceof String)) {
            throw new Error("Expected the field `license_number` to be a primitive type in the JSON string but got " + data['license_number']);
        }
        // ensure the json data is a string
        if (data['specialization'] && !(typeof data['specialization'] === 'string' || data['specialization'] instanceof String)) {
            throw new Error("Expected the field `specialization` to be a primitive type in the JSON string but got " + data['specialization']);
        }
        // ensure the json data is a string
        if (data['experience_level'] && !(typeof data['experience_level'] === 'string' || data['experience_level'] instanceof String)) {
            throw new Error("Expected the field `experience_level` to be a primitive type in the JSON string but got " + data['experience_level']);
        }

        return true;
    }


}

InviteRegisterRequest.RequiredProperties = ["invite_code", "email", "password", "role", "first_name", "last_name", "middle_name", "license_number"];

/**
 * @member {String} invite_code
 */
InviteRegisterRequest.prototype['invite_code'] = undefined;

/**
 * @member {String} email
 */
InviteRegisterRequest.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
InviteRegisterRequest.prototype['phone'] = undefined;

/**
 * @member {String} password
 */
InviteRegisterRequest.prototype['password'] = undefined;

/**
 * @member {module:models/InviteRegisterRequest.RoleEnum} role
 */
InviteRegisterRequest.prototype['role'] = undefined;

/**
 * @member {String} first_name
 */
InviteRegisterRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
InviteRegisterRequest.prototype['last_name'] = undefined;

/**
 * @member {String} middle_name
 */
InviteRegisterRequest.prototype['middle_name'] = undefined;

/**
 * @member {String} license_number
 */
InviteRegisterRequest.prototype['license_number'] = undefined;

/**
 * @member {Number} organization_id
 */
InviteRegisterRequest.prototype['organization_id'] = undefined;

/**
 * @member {Number} sport_type_id
 */
InviteRegisterRequest.prototype['sport_type_id'] = undefined;

/**
 * @member {String} specialization
 */
InviteRegisterRequest.prototype['specialization'] = undefined;

/**
 * @member {String} experience_level
 */
InviteRegisterRequest.prototype['experience_level'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
InviteRegisterRequest['RoleEnum'] = {

    /**
     * value: "coach"
     * @const
     */
    "coach": "coach",

    /**
     * value: "medical"
     * @const
     */
    "medical": "medical"
};



export default InviteRegisterRequest;

