/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InviteDetailsResponse model module.
 * @module models/InviteDetailsResponse
 * @version 1.0.0
 */
class InviteDetailsResponse {
    /**
     * Constructs a new <code>InviteDetailsResponse</code>.
     * @alias module:models/InviteDetailsResponse
     */
    constructor() { 
        
        InviteDetailsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InviteDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InviteDetailsResponse} obj Optional instance to populate.
     * @return {module:models/InviteDetailsResponse} The populated <code>InviteDetailsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteDetailsResponse();

            if (data.hasOwnProperty('invite_code')) {
                obj['invite_code'] = ApiClient.convertToType(data['invite_code'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('license_number')) {
                obj['license_number'] = ApiClient.convertToType(data['license_number'], 'String');
            }
            if (data.hasOwnProperty('organization_id')) {
                obj['organization_id'] = ApiClient.convertToType(data['organization_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteDetailsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteDetailsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['invite_code'] && !(typeof data['invite_code'] === 'string' || data['invite_code'] instanceof String)) {
            throw new Error("Expected the field `invite_code` to be a primitive type in the JSON string but got " + data['invite_code']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['license_number'] && !(typeof data['license_number'] === 'string' || data['license_number'] instanceof String)) {
            throw new Error("Expected the field `license_number` to be a primitive type in the JSON string but got " + data['license_number']);
        }

        return true;
    }


}



/**
 * @member {String} invite_code
 */
InviteDetailsResponse.prototype['invite_code'] = undefined;

/**
 * @member {String} email
 */
InviteDetailsResponse.prototype['email'] = undefined;

/**
 * @member {module:models/InviteDetailsResponse.RoleEnum} role
 */
InviteDetailsResponse.prototype['role'] = undefined;

/**
 * @member {String} license_number
 */
InviteDetailsResponse.prototype['license_number'] = undefined;

/**
 * @member {Number} organization_id
 */
InviteDetailsResponse.prototype['organization_id'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
InviteDetailsResponse['RoleEnum'] = {

    /**
     * value: "coach"
     * @const
     */
    "coach": "coach",

    /**
     * value: "medical"
     * @const
     */
    "medical": "medical"
};



export default InviteDetailsResponse;

