/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InviteCreateRequest model module.
 * @module models/InviteCreateRequest
 * @version 1.0.0
 */
class InviteCreateRequest {
    /**
     * Constructs a new <code>InviteCreateRequest</code>.
     * @alias module:models/InviteCreateRequest
     * @param email {String} 
     * @param role {module:models/InviteCreateRequest.RoleEnum} 
     * @param fullName {String} 
     * @param licenseNumber {String} 
     * @param organizationId {Number} 
     */
    constructor(email, role, fullName, licenseNumber, organizationId) { 
        
        InviteCreateRequest.initialize(this, email, role, fullName, licenseNumber, organizationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, role, fullName, licenseNumber, organizationId) { 
        obj['email'] = email;
        obj['role'] = role;
        obj['full_name'] = fullName;
        obj['license_number'] = licenseNumber;
        obj['organization_id'] = organizationId;
    }

    /**
     * Constructs a <code>InviteCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InviteCreateRequest} obj Optional instance to populate.
     * @return {module:models/InviteCreateRequest} The populated <code>InviteCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteCreateRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('full_name')) {
                obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
            }
            if (data.hasOwnProperty('license_number')) {
                obj['license_number'] = ApiClient.convertToType(data['license_number'], 'String');
            }
            if (data.hasOwnProperty('organization_id')) {
                obj['organization_id'] = ApiClient.convertToType(data['organization_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InviteCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['full_name'] && !(typeof data['full_name'] === 'string' || data['full_name'] instanceof String)) {
            throw new Error("Expected the field `full_name` to be a primitive type in the JSON string but got " + data['full_name']);
        }
        // ensure the json data is a string
        if (data['license_number'] && !(typeof data['license_number'] === 'string' || data['license_number'] instanceof String)) {
            throw new Error("Expected the field `license_number` to be a primitive type in the JSON string but got " + data['license_number']);
        }

        return true;
    }


}

InviteCreateRequest.RequiredProperties = ["email", "role", "full_name", "license_number", "organization_id"];

/**
 * @member {String} email
 */
InviteCreateRequest.prototype['email'] = undefined;

/**
 * @member {module:models/InviteCreateRequest.RoleEnum} role
 */
InviteCreateRequest.prototype['role'] = undefined;

/**
 * @member {String} full_name
 */
InviteCreateRequest.prototype['full_name'] = undefined;

/**
 * @member {String} license_number
 */
InviteCreateRequest.prototype['license_number'] = undefined;

/**
 * @member {Number} organization_id
 */
InviteCreateRequest.prototype['organization_id'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
InviteCreateRequest['RoleEnum'] = {

    /**
     * value: "coach"
     * @const
     */
    "coach": "coach",

    /**
     * value: "medical"
     * @const
     */
    "medical": "medical"
};



export default InviteCreateRequest;

