/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MedicalAssigment model module.
 * @module models/MedicalAssigment
 * @version 1.0.0
 */
class MedicalAssigment {
    /**
     * Constructs a new <code>MedicalAssigment</code>.
     * @alias module:models/MedicalAssigment
     */
    constructor() { 
        
        MedicalAssigment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MedicalAssigment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/MedicalAssigment} obj Optional instance to populate.
     * @return {module:models/MedicalAssigment} The populated <code>MedicalAssigment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MedicalAssigment();

            if (data.hasOwnProperty('athlete_id')) {
                obj['athlete_id'] = ApiClient.convertToType(data['athlete_id'], 'Number');
            }
            if (data.hasOwnProperty('athlete_code')) {
                obj['athlete_code'] = ApiClient.convertToType(data['athlete_code'], 'String');
            }
            if (data.hasOwnProperty('assigned_by')) {
                obj['assigned_by'] = ApiClient.convertToType(data['assigned_by'], 'Number');
            }
            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'Number');
            }
            if (data.hasOwnProperty('sport_type')) {
                obj['sport_type'] = ApiClient.convertToType(data['sport_type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MedicalAssigment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MedicalAssigment</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['athlete_code'] && !(typeof data['athlete_code'] === 'string' || data['athlete_code'] instanceof String)) {
            throw new Error("Expected the field `athlete_code` to be a primitive type in the JSON string but got " + data['athlete_code']);
        }
        // ensure the json data is a string
        if (data['sport_type'] && !(typeof data['sport_type'] === 'string' || data['sport_type'] instanceof String)) {
            throw new Error("Expected the field `sport_type` to be a primitive type in the JSON string but got " + data['sport_type']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} athlete_id
 */
MedicalAssigment.prototype['athlete_id'] = undefined;

/**
 * @member {String} athlete_code
 */
MedicalAssigment.prototype['athlete_code'] = undefined;

/**
 * @member {Number} assigned_by
 */
MedicalAssigment.prototype['assigned_by'] = undefined;

/**
 * @member {Number} age
 */
MedicalAssigment.prototype['age'] = undefined;

/**
 * @member {String} sport_type
 */
MedicalAssigment.prototype['sport_type'] = undefined;

/**
 * @member {String} status
 */
MedicalAssigment.prototype['status'] = undefined;






export default MedicalAssigment;

