/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MedicalstaffProfileResponse model module.
 * @module models/MedicalstaffProfileResponse
 * @version 1.0.0
 */
class MedicalstaffProfileResponse {
    /**
     * Constructs a new <code>MedicalstaffProfileResponse</code>.
     * @alias module:models/MedicalstaffProfileResponse
     */
    constructor() { 
        
        MedicalstaffProfileResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MedicalstaffProfileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/MedicalstaffProfileResponse} obj Optional instance to populate.
     * @return {module:models/MedicalstaffProfileResponse} The populated <code>MedicalstaffProfileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MedicalstaffProfileResponse();

            if (data.hasOwnProperty('medicalstaff_id')) {
                obj['medicalstaff_id'] = ApiClient.convertToType(data['medicalstaff_id'], 'Number');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('specialization')) {
                obj['specialization'] = ApiClient.convertToType(data['specialization'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MedicalstaffProfileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MedicalstaffProfileResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['specialization'] && !(typeof data['specialization'] === 'string' || data['specialization'] instanceof String)) {
            throw new Error("Expected the field `specialization` to be a primitive type in the JSON string but got " + data['specialization']);
        }

        return true;
    }


}



/**
 * @member {Number} medicalstaff_id
 */
MedicalstaffProfileResponse.prototype['medicalstaff_id'] = undefined;

/**
 * @member {String} first_name
 */
MedicalstaffProfileResponse.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
MedicalstaffProfileResponse.prototype['last_name'] = undefined;

/**
 * @member {String} middle_name
 */
MedicalstaffProfileResponse.prototype['middle_name'] = undefined;

/**
 * @member {String} specialization
 */
MedicalstaffProfileResponse.prototype['specialization'] = undefined;






export default MedicalstaffProfileResponse;

