/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MedicalstaffProfileResponse from './MedicalstaffProfileResponse';

/**
 * The TeamGetMedicalstaffResponse model module.
 * @module models/TeamGetMedicalstaffResponse
 * @version 1.0.0
 */
class TeamGetMedicalstaffResponse {
    /**
     * Constructs a new <code>TeamGetMedicalstaffResponse</code>.
     * @alias module:models/TeamGetMedicalstaffResponse
     */
    constructor() { 
        
        TeamGetMedicalstaffResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamGetMedicalstaffResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamGetMedicalstaffResponse} obj Optional instance to populate.
     * @return {module:models/TeamGetMedicalstaffResponse} The populated <code>TeamGetMedicalstaffResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamGetMedicalstaffResponse();

            if (data.hasOwnProperty('medicalstaff')) {
                obj['medicalstaff'] = ApiClient.convertToType(data['medicalstaff'], [MedicalstaffProfileResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamGetMedicalstaffResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamGetMedicalstaffResponse</code>.
     */
    static validateJSON(data) {
        if (data['medicalstaff']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['medicalstaff'])) {
                throw new Error("Expected the field `medicalstaff` to be an array in the JSON data but got " + data['medicalstaff']);
            }
            // validate the optional field `medicalstaff` (array)
            for (const item of data['medicalstaff']) {
                MedicalstaffProfileResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/MedicalstaffProfileResponse>} medicalstaff
 */
TeamGetMedicalstaffResponse.prototype['medicalstaff'] = undefined;






export default TeamGetMedicalstaffResponse;

