/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamJoin from './TeamJoin';

/**
 * The TeamJoinsListResponse model module.
 * @module models/TeamJoinsListResponse
 * @version 1.0.0
 */
class TeamJoinsListResponse {
    /**
     * Constructs a new <code>TeamJoinsListResponse</code>.
     * @alias module:models/TeamJoinsListResponse
     */
    constructor() { 
        
        TeamJoinsListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamJoinsListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamJoinsListResponse} obj Optional instance to populate.
     * @return {module:models/TeamJoinsListResponse} The populated <code>TeamJoinsListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamJoinsListResponse();

            if (data.hasOwnProperty('joins')) {
                obj['joins'] = ApiClient.convertToType(data['joins'], [TeamJoin]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamJoinsListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamJoinsListResponse</code>.
     */
    static validateJSON(data) {
        if (data['joins']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['joins'])) {
                throw new Error("Expected the field `joins` to be an array in the JSON data but got " + data['joins']);
            }
            // validate the optional field `joins` (array)
            for (const item of data['joins']) {
                TeamJoin.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/TeamJoin>} joins
 */
TeamJoinsListResponse.prototype['joins'] = undefined;






export default TeamJoinsListResponse;

