/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamsJoinPostRequest model module.
 * @module models/TeamsJoinPostRequest
 * @version 1.0.0
 */
class TeamsJoinPostRequest {
    /**
     * Constructs a new <code>TeamsJoinPostRequest</code>.
     * @alias module:models/TeamsJoinPostRequest
     * @param teamId {Number} 
     */
    constructor(teamId) { 
        
        TeamsJoinPostRequest.initialize(this, teamId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, teamId) { 
        obj['team_id'] = teamId;
    }

    /**
     * Constructs a <code>TeamsJoinPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamsJoinPostRequest} obj Optional instance to populate.
     * @return {module:models/TeamsJoinPostRequest} The populated <code>TeamsJoinPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamsJoinPostRequest();

            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamsJoinPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamsJoinPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TeamsJoinPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TeamsJoinPostRequest.RequiredProperties = ["team_id"];

/**
 * @member {Number} team_id
 */
TeamsJoinPostRequest.prototype['team_id'] = undefined;






export default TeamsJoinPostRequest;

