/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamAthleteStatusResponse model module.
 * @module models/TeamAthleteStatusResponse
 * @version 1.0.0
 */
class TeamAthleteStatusResponse {
    /**
     * Constructs a new <code>TeamAthleteStatusResponse</code>.
     * @alias module:models/TeamAthleteStatusResponse
     */
    constructor() { 
        
        TeamAthleteStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamAthleteStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamAthleteStatusResponse} obj Optional instance to populate.
     * @return {module:models/TeamAthleteStatusResponse} The populated <code>TeamAthleteStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamAthleteStatusResponse();

            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'Number');
            }
            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('requested_at')) {
                obj['requested_at'] = ApiClient.convertToType(data['requested_at'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamAthleteStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamAthleteStatusResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['team_name'] && !(typeof data['team_name'] === 'string' || data['team_name'] instanceof String)) {
            throw new Error("Expected the field `team_name` to be a primitive type in the JSON string but got " + data['team_name']);
        }
        // ensure the json data is a string
        if (data['requested_at'] && !(typeof data['requested_at'] === 'string' || data['requested_at'] instanceof String)) {
            throw new Error("Expected the field `requested_at` to be a primitive type in the JSON string but got " + data['requested_at']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} request_id
 */
TeamAthleteStatusResponse.prototype['request_id'] = undefined;

/**
 * @member {String} team_name
 */
TeamAthleteStatusResponse.prototype['team_name'] = undefined;

/**
 * @member {String} requested_at
 */
TeamAthleteStatusResponse.prototype['requested_at'] = undefined;

/**
 * @member {String} status
 */
TeamAthleteStatusResponse.prototype['status'] = undefined;






export default TeamAthleteStatusResponse;

