/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoachProfileResponse from './CoachProfileResponse';

/**
 * The TeamGetCoachesResponse model module.
 * @module models/TeamGetCoachesResponse
 * @version 1.0.0
 */
class TeamGetCoachesResponse {
    /**
     * Constructs a new <code>TeamGetCoachesResponse</code>.
     * @alias module:models/TeamGetCoachesResponse
     */
    constructor() { 
        
        TeamGetCoachesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamGetCoachesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamGetCoachesResponse} obj Optional instance to populate.
     * @return {module:models/TeamGetCoachesResponse} The populated <code>TeamGetCoachesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamGetCoachesResponse();

            if (data.hasOwnProperty('coaches')) {
                obj['coaches'] = ApiClient.convertToType(data['coaches'], [CoachProfileResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamGetCoachesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamGetCoachesResponse</code>.
     */
    static validateJSON(data) {
        if (data['coaches']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['coaches'])) {
                throw new Error("Expected the field `coaches` to be an array in the JSON data but got " + data['coaches']);
            }
            // validate the optional field `coaches` (array)
            for (const item of data['coaches']) {
                CoachProfileResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/CoachProfileResponse>} coaches
 */
TeamGetCoachesResponse.prototype['coaches'] = undefined;






export default TeamGetCoachesResponse;

