/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamJoin model module.
 * @module models/TeamJoin
 * @version 1.0.0
 */
class TeamJoin {
    /**
     * Constructs a new <code>TeamJoin</code>.
     * @alias module:models/TeamJoin
     */
    constructor() { 
        
        TeamJoin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamJoin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamJoin} obj Optional instance to populate.
     * @return {module:models/TeamJoin} The populated <code>TeamJoin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamJoin();

            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'Number');
            }
            if (data.hasOwnProperty('second_name')) {
                obj['second_name'] = ApiClient.convertToType(data['second_name'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('request_date')) {
                obj['request_date'] = ApiClient.convertToType(data['request_date'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamJoin</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamJoin</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['second_name'] && !(typeof data['second_name'] === 'string' || data['second_name'] instanceof String)) {
            throw new Error("Expected the field `second_name` to be a primitive type in the JSON string but got " + data['second_name']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['team_name'] && !(typeof data['team_name'] === 'string' || data['team_name'] instanceof String)) {
            throw new Error("Expected the field `team_name` to be a primitive type in the JSON string but got " + data['team_name']);
        }
        // ensure the json data is a string
        if (data['request_date'] && !(typeof data['request_date'] === 'string' || data['request_date'] instanceof String)) {
            throw new Error("Expected the field `request_date` to be a primitive type in the JSON string but got " + data['request_date']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} request_id
 */
TeamJoin.prototype['request_id'] = undefined;

/**
 * @member {String} second_name
 */
TeamJoin.prototype['second_name'] = undefined;

/**
 * @member {String} first_name
 */
TeamJoin.prototype['first_name'] = undefined;

/**
 * @member {String} middle_name
 */
TeamJoin.prototype['middle_name'] = undefined;

/**
 * @member {String} email
 */
TeamJoin.prototype['email'] = undefined;

/**
 * @member {String} team_name
 */
TeamJoin.prototype['team_name'] = undefined;

/**
 * @member {String} request_date
 */
TeamJoin.prototype['request_date'] = undefined;

/**
 * @member {String} status
 */
TeamJoin.prototype['status'] = undefined;






export default TeamJoin;

