/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Team from './Team';

/**
 * The TeamResponse model module.
 * @module models/TeamResponse
 * @version 1.0.0
 */
class TeamResponse {
    /**
     * Constructs a new <code>TeamResponse</code>.
     * @alias module:models/TeamResponse
     */
    constructor() { 
        
        TeamResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamResponse} obj Optional instance to populate.
     * @return {module:models/TeamResponse} The populated <code>TeamResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamResponse();

            if (data.hasOwnProperty('teams')) {
                obj['teams'] = ApiClient.convertToType(data['teams'], [Team]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamResponse</code>.
     */
    static validateJSON(data) {
        if (data['teams']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teams'])) {
                throw new Error("Expected the field `teams` to be an array in the JSON data but got " + data['teams']);
            }
            // validate the optional field `teams` (array)
            for (const item of data['teams']) {
                Team.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/Team>} teams
 */
TeamResponse.prototype['teams'] = undefined;






export default TeamResponse;

