/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Team model module.
 * @module models/Team
 * @version 1.0.0
 */
class Team {
    /**
     * Constructs a new <code>Team</code>.
     * @alias module:models/Team
     * @param teamId {Number} 
     * @param teamName {String} 
     * @param sportType {String} 
     * @param countAthletes {Number} 
     */
    constructor(teamId, teamName, sportType, countAthletes) { 
        
        Team.initialize(this, teamId, teamName, sportType, countAthletes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, teamId, teamName, sportType, countAthletes) { 
        obj['team_id'] = teamId;
        obj['team_name'] = teamName;
        obj['sport_type'] = sportType;
        obj['count_athletes'] = countAthletes;
    }

    /**
     * Constructs a <code>Team</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/Team} obj Optional instance to populate.
     * @return {module:models/Team} The populated <code>Team</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Team();

            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('sport_type')) {
                obj['sport_type'] = ApiClient.convertToType(data['sport_type'], 'String');
            }
            if (data.hasOwnProperty('count_athletes')) {
                obj['count_athletes'] = ApiClient.convertToType(data['count_athletes'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Team</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Team</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Team.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['team_name'] && !(typeof data['team_name'] === 'string' || data['team_name'] instanceof String)) {
            throw new Error("Expected the field `team_name` to be a primitive type in the JSON string but got " + data['team_name']);
        }
        // ensure the json data is a string
        if (data['sport_type'] && !(typeof data['sport_type'] === 'string' || data['sport_type'] instanceof String)) {
            throw new Error("Expected the field `sport_type` to be a primitive type in the JSON string but got " + data['sport_type']);
        }

        return true;
    }


}

Team.RequiredProperties = ["team_id", "team_name", "sport_type", "count_athletes"];

/**
 * @member {Number} team_id
 */
Team.prototype['team_id'] = undefined;

/**
 * @member {String} team_name
 */
Team.prototype['team_name'] = undefined;

/**
 * @member {String} sport_type
 */
Team.prototype['sport_type'] = undefined;

/**
 * @member {Number} count_athletes
 */
Team.prototype['count_athletes'] = undefined;






export default Team;

