/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MedicalAssigment from './MedicalAssigment';

/**
 * The TeamGetMedicalAssignmentsResponse model module.
 * @module models/TeamGetMedicalAssignmentsResponse
 * @version 1.0.0
 */
class TeamGetMedicalAssignmentsResponse {
    /**
     * Constructs a new <code>TeamGetMedicalAssignmentsResponse</code>.
     * @alias module:models/TeamGetMedicalAssignmentsResponse
     */
    constructor() { 
        
        TeamGetMedicalAssignmentsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamGetMedicalAssignmentsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TeamGetMedicalAssignmentsResponse} obj Optional instance to populate.
     * @return {module:models/TeamGetMedicalAssignmentsResponse} The populated <code>TeamGetMedicalAssignmentsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamGetMedicalAssignmentsResponse();

            if (data.hasOwnProperty('athletes')) {
                obj['athletes'] = ApiClient.convertToType(data['athletes'], [MedicalAssigment]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamGetMedicalAssignmentsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamGetMedicalAssignmentsResponse</code>.
     */
    static validateJSON(data) {
        if (data['athletes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['athletes'])) {
                throw new Error("Expected the field `athletes` to be an array in the JSON data but got " + data['athletes']);
            }
            // validate the optional field `athletes` (array)
            for (const item of data['athletes']) {
                MedicalAssigment.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/MedicalAssigment>} athletes
 */
TeamGetMedicalAssignmentsResponse.prototype['athletes'] = undefined;






export default TeamGetMedicalAssignmentsResponse;

