/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingPlansItemsItemIdOverridePostRequest model module.
 * @module models/TrainingPlansItemsItemIdOverridePostRequest
 * @version 1.0.0
 */
class TrainingPlansItemsItemIdOverridePostRequest {
    /**
     * Constructs a new <code>TrainingPlansItemsItemIdOverridePostRequest</code>.
     * @alias module:models/TrainingPlansItemsItemIdOverridePostRequest
     * @param athleteId {Number} 
     * @param customValue {String} 
     */
    constructor(athleteId, customValue) { 
        
        TrainingPlansItemsItemIdOverridePostRequest.initialize(this, athleteId, customValue);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, athleteId, customValue) { 
        obj['athlete_id'] = athleteId;
        obj['custom_value'] = customValue;
    }

    /**
     * Constructs a <code>TrainingPlansItemsItemIdOverridePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlansItemsItemIdOverridePostRequest} obj Optional instance to populate.
     * @return {module:models/TrainingPlansItemsItemIdOverridePostRequest} The populated <code>TrainingPlansItemsItemIdOverridePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlansItemsItemIdOverridePostRequest();

            if (data.hasOwnProperty('athlete_id')) {
                obj['athlete_id'] = ApiClient.convertToType(data['athlete_id'], 'Number');
            }
            if (data.hasOwnProperty('custom_value')) {
                obj['custom_value'] = ApiClient.convertToType(data['custom_value'], 'String');
            }
            if (data.hasOwnProperty('custom_notes')) {
                obj['custom_notes'] = ApiClient.convertToType(data['custom_notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlansItemsItemIdOverridePostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlansItemsItemIdOverridePostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrainingPlansItemsItemIdOverridePostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['custom_value'] && !(typeof data['custom_value'] === 'string' || data['custom_value'] instanceof String)) {
            throw new Error("Expected the field `custom_value` to be a primitive type in the JSON string but got " + data['custom_value']);
        }
        // ensure the json data is a string
        if (data['custom_notes'] && !(typeof data['custom_notes'] === 'string' || data['custom_notes'] instanceof String)) {
            throw new Error("Expected the field `custom_notes` to be a primitive type in the JSON string but got " + data['custom_notes']);
        }

        return true;
    }


}

TrainingPlansItemsItemIdOverridePostRequest.RequiredProperties = ["athlete_id", "custom_value"];

/**
 * @member {Number} athlete_id
 */
TrainingPlansItemsItemIdOverridePostRequest.prototype['athlete_id'] = undefined;

/**
 * @member {String} custom_value
 */
TrainingPlansItemsItemIdOverridePostRequest.prototype['custom_value'] = undefined;

/**
 * @member {String} custom_notes
 */
TrainingPlansItemsItemIdOverridePostRequest.prototype['custom_notes'] = undefined;






export default TrainingPlansItemsItemIdOverridePostRequest;

