/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingPlanCreate model module.
 * @module models/TrainingPlanCreate
 * @version 1.0.0
 */
class TrainingPlanCreate {
    /**
     * Constructs a new <code>TrainingPlanCreate</code>.
     * @alias module:models/TrainingPlanCreate
     * @param title {String} 
     * @param teamId {Number} 
     * @param startDate {Date} 
     * @param endDate {Date} 
     * @param periodTypeId {Number} 
     */
    constructor(title, teamId, startDate, endDate, periodTypeId) { 
        
        TrainingPlanCreate.initialize(this, title, teamId, startDate, endDate, periodTypeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, teamId, startDate, endDate, periodTypeId) { 
        obj['title'] = title;
        obj['team_id'] = teamId;
        obj['start_date'] = startDate;
        obj['end_date'] = endDate;
        obj['period_type_id'] = periodTypeId;
    }

    /**
     * Constructs a <code>TrainingPlanCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlanCreate} obj Optional instance to populate.
     * @return {module:models/TrainingPlanCreate} The populated <code>TrainingPlanCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlanCreate();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('period_type_id')) {
                obj['period_type_id'] = ApiClient.convertToType(data['period_type_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlanCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlanCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrainingPlanCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

TrainingPlanCreate.RequiredProperties = ["title", "team_id", "start_date", "end_date", "period_type_id"];

/**
 * @member {String} title
 */
TrainingPlanCreate.prototype['title'] = undefined;

/**
 * @member {Number} team_id
 */
TrainingPlanCreate.prototype['team_id'] = undefined;

/**
 * @member {String} description
 */
TrainingPlanCreate.prototype['description'] = undefined;

/**
 * @member {Date} start_date
 */
TrainingPlanCreate.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
TrainingPlanCreate.prototype['end_date'] = undefined;

/**
 * @member {String} status
 */
TrainingPlanCreate.prototype['status'] = undefined;

/**
 * @member {Number} period_type_id
 */
TrainingPlanCreate.prototype['period_type_id'] = undefined;






export default TrainingPlanCreate;

