/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingPlanItemCreate model module.
 * @module models/TrainingPlanItemCreate
 * @version 1.0.0
 */
class TrainingPlanItemCreate {
    /**
     * Constructs a new <code>TrainingPlanItemCreate</code>.
     * @alias module:models/TrainingPlanItemCreate
     * @param workoutDate {Date} 
     * @param time {String} 
     * @param sessionTypeId {Number} 
     * @param formatTypeId {Number} 
     * @param value {Number} 
     */
    constructor(workoutDate, time, sessionTypeId, formatTypeId, value) { 
        
        TrainingPlanItemCreate.initialize(this, workoutDate, time, sessionTypeId, formatTypeId, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workoutDate, time, sessionTypeId, formatTypeId, value) { 
        obj['workout_date'] = workoutDate;
        obj['time'] = time;
        obj['session_type_id'] = sessionTypeId;
        obj['format_type_id'] = formatTypeId;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TrainingPlanItemCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlanItemCreate} obj Optional instance to populate.
     * @return {module:models/TrainingPlanItemCreate} The populated <code>TrainingPlanItemCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlanItemCreate();

            if (data.hasOwnProperty('workout_date')) {
                obj['workout_date'] = ApiClient.convertToType(data['workout_date'], 'Date');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
            if (data.hasOwnProperty('session_type_id')) {
                obj['session_type_id'] = ApiClient.convertToType(data['session_type_id'], 'Number');
            }
            if (data.hasOwnProperty('format_type_id')) {
                obj['format_type_id'] = ApiClient.convertToType(data['format_type_id'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlanItemCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlanItemCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrainingPlanItemCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

TrainingPlanItemCreate.RequiredProperties = ["workout_date", "time", "session_type_id", "format_type_id", "value"];

/**
 * @member {Date} workout_date
 */
TrainingPlanItemCreate.prototype['workout_date'] = undefined;

/**
 * @member {String} time
 */
TrainingPlanItemCreate.prototype['time'] = undefined;

/**
 * @member {Number} session_type_id
 */
TrainingPlanItemCreate.prototype['session_type_id'] = undefined;

/**
 * @member {Number} format_type_id
 */
TrainingPlanItemCreate.prototype['format_type_id'] = undefined;

/**
 * @member {Number} value
 */
TrainingPlanItemCreate.prototype['value'] = undefined;

/**
 * @member {String} description
 */
TrainingPlanItemCreate.prototype['description'] = undefined;






export default TrainingPlanItemCreate;

