/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingPlansPlanIdAssignPostRequest model module.
 * @module models/TrainingPlansPlanIdAssignPostRequest
 * @version 1.0.0
 */
class TrainingPlansPlanIdAssignPostRequest {
    /**
     * Constructs a new <code>TrainingPlansPlanIdAssignPostRequest</code>.
     * @alias module:models/TrainingPlansPlanIdAssignPostRequest
     * @param athleteIds {Array.<Number>} 
     * @param startDate {Date} 
     */
    constructor(athleteIds, startDate) { 
        
        TrainingPlansPlanIdAssignPostRequest.initialize(this, athleteIds, startDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, athleteIds, startDate) { 
        obj['athlete_ids'] = athleteIds;
        obj['start_date'] = startDate;
    }

    /**
     * Constructs a <code>TrainingPlansPlanIdAssignPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlansPlanIdAssignPostRequest} obj Optional instance to populate.
     * @return {module:models/TrainingPlansPlanIdAssignPostRequest} The populated <code>TrainingPlansPlanIdAssignPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlansPlanIdAssignPostRequest();

            if (data.hasOwnProperty('athlete_ids')) {
                obj['athlete_ids'] = ApiClient.convertToType(data['athlete_ids'], ['Number']);
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlansPlanIdAssignPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlansPlanIdAssignPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrainingPlansPlanIdAssignPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['athlete_ids'])) {
            throw new Error("Expected the field `athlete_ids` to be an array in the JSON data but got " + data['athlete_ids']);
        }

        return true;
    }


}

TrainingPlansPlanIdAssignPostRequest.RequiredProperties = ["athlete_ids", "start_date"];

/**
 * @member {Array.<Number>} athlete_ids
 */
TrainingPlansPlanIdAssignPostRequest.prototype['athlete_ids'] = undefined;

/**
 * @member {Date} start_date
 */
TrainingPlansPlanIdAssignPostRequest.prototype['start_date'] = undefined;






export default TrainingPlansPlanIdAssignPostRequest;

