/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingPlan model module.
 * @module models/TrainingPlan
 * @version 1.0.0
 */
class TrainingPlan {
    /**
     * Constructs a new <code>TrainingPlan</code>.
     * @alias module:models/TrainingPlan
     */
    constructor() { 
        
        TrainingPlan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrainingPlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlan} obj Optional instance to populate.
     * @return {module:models/TrainingPlan} The populated <code>TrainingPlan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlan();

            if (data.hasOwnProperty('plan_id')) {
                obj['plan_id'] = ApiClient.convertToType(data['plan_id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlan</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlan</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['team_name'] && !(typeof data['team_name'] === 'string' || data['team_name'] instanceof String)) {
            throw new Error("Expected the field `team_name` to be a primitive type in the JSON string but got " + data['team_name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {Number} plan_id
 */
TrainingPlan.prototype['plan_id'] = undefined;

/**
 * @member {String} title
 */
TrainingPlan.prototype['title'] = undefined;

/**
 * @member {String} team_name
 */
TrainingPlan.prototype['team_name'] = undefined;

/**
 * @member {Date} start_date
 */
TrainingPlan.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
TrainingPlan.prototype['end_date'] = undefined;

/**
 * @member {String} status
 */
TrainingPlan.prototype['status'] = undefined;

/**
 * @member {String} description
 */
TrainingPlan.prototype['description'] = undefined;






export default TrainingPlan;

