/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingPlansPlanIdItemsPostRequest model module.
 * @module models/TrainingPlansPlanIdItemsPostRequest
 * @version 1.0.0
 */
class TrainingPlansPlanIdItemsPostRequest {
    /**
     * Constructs a new <code>TrainingPlansPlanIdItemsPostRequest</code>.
     * @alias module:models/TrainingPlansPlanIdItemsPostRequest
     * @param sessionDate {Date} 
     * @param sessionTypeId {Number} 
     * @param formatTypeId {Number} 
     * @param value {String} 
     */
    constructor(sessionDate, sessionTypeId, formatTypeId, value) { 
        
        TrainingPlansPlanIdItemsPostRequest.initialize(this, sessionDate, sessionTypeId, formatTypeId, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sessionDate, sessionTypeId, formatTypeId, value) { 
        obj['session_date'] = sessionDate;
        obj['session_type_id'] = sessionTypeId;
        obj['format_type_id'] = formatTypeId;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TrainingPlansPlanIdItemsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlansPlanIdItemsPostRequest} obj Optional instance to populate.
     * @return {module:models/TrainingPlansPlanIdItemsPostRequest} The populated <code>TrainingPlansPlanIdItemsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlansPlanIdItemsPostRequest();

            if (data.hasOwnProperty('session_date')) {
                obj['session_date'] = ApiClient.convertToType(data['session_date'], 'Date');
            }
            if (data.hasOwnProperty('session_type_id')) {
                obj['session_type_id'] = ApiClient.convertToType(data['session_type_id'], 'Number');
            }
            if (data.hasOwnProperty('format_type_id')) {
                obj['format_type_id'] = ApiClient.convertToType(data['format_type_id'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlansPlanIdItemsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlansPlanIdItemsPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrainingPlansPlanIdItemsPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}

TrainingPlansPlanIdItemsPostRequest.RequiredProperties = ["session_date", "session_type_id", "format_type_id", "value"];

/**
 * @member {Date} session_date
 */
TrainingPlansPlanIdItemsPostRequest.prototype['session_date'] = undefined;

/**
 * @member {Number} session_type_id
 */
TrainingPlansPlanIdItemsPostRequest.prototype['session_type_id'] = undefined;

/**
 * @member {Number} format_type_id
 */
TrainingPlansPlanIdItemsPostRequest.prototype['format_type_id'] = undefined;

/**
 * @member {String} value
 */
TrainingPlansPlanIdItemsPostRequest.prototype['value'] = undefined;

/**
 * @member {String} notes
 */
TrainingPlansPlanIdItemsPostRequest.prototype['notes'] = undefined;






export default TrainingPlansPlanIdItemsPostRequest;

