/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrainingPlan from './TrainingPlan';

/**
 * The TrainingPlanListResponse model module.
 * @module models/TrainingPlanListResponse
 * @version 1.0.0
 */
class TrainingPlanListResponse {
    /**
     * Constructs a new <code>TrainingPlanListResponse</code>.
     * @alias module:models/TrainingPlanListResponse
     */
    constructor() { 
        
        TrainingPlanListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrainingPlanListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TrainingPlanListResponse} obj Optional instance to populate.
     * @return {module:models/TrainingPlanListResponse} The populated <code>TrainingPlanListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingPlanListResponse();

            if (data.hasOwnProperty('plans')) {
                obj['plans'] = ApiClient.convertToType(data['plans'], [TrainingPlan]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrainingPlanListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrainingPlanListResponse</code>.
     */
    static validateJSON(data) {
        if (data['plans']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['plans'])) {
                throw new Error("Expected the field `plans` to be an array in the JSON data but got " + data['plans']);
            }
            // validate the optional field `plans` (array)
            for (const item of data['plans']) {
                TrainingPlan.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:models/TrainingPlan>} plans
 */
TrainingPlanListResponse.prototype['plans'] = undefined;






export default TrainingPlanListResponse;

