/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.TrainingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrainingApi', function() {
    describe('trainingPlansItemsItemIdDelete', function() {
      it('should call trainingPlansItemsItemIdDelete successfully', function(done) {
        //uncomment below and update the code to test trainingPlansItemsItemIdDelete
        //instance.trainingPlansItemsItemIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trainingPlansItemsItemIdOverridePost', function() {
      it('should call trainingPlansItemsItemIdOverridePost successfully', function(done) {
        //uncomment below and update the code to test trainingPlansItemsItemIdOverridePost
        //instance.trainingPlansItemsItemIdOverridePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trainingPlansPlanIdAssignPost', function() {
      it('should call trainingPlansPlanIdAssignPost successfully', function(done) {
        //uncomment below and update the code to test trainingPlansPlanIdAssignPost
        //instance.trainingPlansPlanIdAssignPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trainingPlansPlanIdItemsPost', function() {
      it('should call trainingPlansPlanIdItemsPost successfully', function(done) {
        //uncomment below and update the code to test trainingPlansPlanIdItemsPost
        //instance.trainingPlansPlanIdItemsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trainingPlansPost', function() {
      it('should call trainingPlansPost successfully', function(done) {
        //uncomment below and update the code to test trainingPlansPost
        //instance.trainingPlansPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
