/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.AthleteIndicatorResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AthleteIndicatorResponse', function() {
    it('should create an instance of AthleteIndicatorResponse', function() {
      // uncomment below and update the code to test AthleteIndicatorResponse
      //var instance = new Api.AthleteIndicatorResponse();
      //expect(instance).to.be.a(Api.AthleteIndicatorResponse);
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new Api.AthleteIndicatorResponse();
      //expect(instance).to.be();
    });

    it('should have the property hrv (base name: "hrv")', function() {
      // uncomment below and update the code to test the property hrv
      //var instance = new Api.AthleteIndicatorResponse();
      //expect(instance).to.be();
    });

    it('should have the property morningPulse (base name: "morning_pulse")', function() {
      // uncomment below and update the code to test the property morningPulse
      //var instance = new Api.AthleteIndicatorResponse();
      //expect(instance).to.be();
    });

    it('should have the property eveningPulse (base name: "evening_pulse")', function() {
      // uncomment below and update the code to test the property eveningPulse
      //var instance = new Api.AthleteIndicatorResponse();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new Api.AthleteIndicatorResponse();
      //expect(instance).to.be();
    });

  });

}));
