/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.BiometricInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BiometricInput', function() {
    it('should create an instance of BiometricInput', function() {
      // uncomment below and update the code to test BiometricInput
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be.a(Api.BiometricInput);
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be();
    });

    it('should have the property timeOfDay (base name: "time_of_day")', function() {
      // uncomment below and update the code to test the property timeOfDay
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be();
    });

    it('should have the property pulse (base name: "pulse")', function() {
      // uncomment below and update the code to test the property pulse
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be();
    });

    it('should have the property HRV (base name: "HRV")', function() {
      // uncomment below and update the code to test the property HRV
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new Api.BiometricInput();
      //expect(instance).to.be();
    });

  });

}));
