/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.TrainingPlansPlanIdItemsPostRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrainingPlansPlanIdItemsPostRequest', function() {
    it('should create an instance of TrainingPlansPlanIdItemsPostRequest', function() {
      // uncomment below and update the code to test TrainingPlansPlanIdItemsPostRequest
      //var instance = new Api.TrainingPlansPlanIdItemsPostRequest();
      //expect(instance).to.be.a(Api.TrainingPlansPlanIdItemsPostRequest);
    });

    it('should have the property sessionDate (base name: "session_date")', function() {
      // uncomment below and update the code to test the property sessionDate
      //var instance = new Api.TrainingPlansPlanIdItemsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property sessionTypeId (base name: "session_type_id")', function() {
      // uncomment below and update the code to test the property sessionTypeId
      //var instance = new Api.TrainingPlansPlanIdItemsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property formatTypeId (base name: "format_type_id")', function() {
      // uncomment below and update the code to test the property formatTypeId
      //var instance = new Api.TrainingPlansPlanIdItemsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new Api.TrainingPlansPlanIdItemsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new Api.TrainingPlansPlanIdItemsPostRequest();
      //expect(instance).to.be();
    });

  });

}));
