/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.TrainingPlansItemsItemIdOverridePostRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrainingPlansItemsItemIdOverridePostRequest', function() {
    it('should create an instance of TrainingPlansItemsItemIdOverridePostRequest', function() {
      // uncomment below and update the code to test TrainingPlansItemsItemIdOverridePostRequest
      //var instance = new Api.TrainingPlansItemsItemIdOverridePostRequest();
      //expect(instance).to.be.a(Api.TrainingPlansItemsItemIdOverridePostRequest);
    });

    it('should have the property athleteId (base name: "athlete_id")', function() {
      // uncomment below and update the code to test the property athleteId
      //var instance = new Api.TrainingPlansItemsItemIdOverridePostRequest();
      //expect(instance).to.be();
    });

    it('should have the property customValue (base name: "custom_value")', function() {
      // uncomment below and update the code to test the property customValue
      //var instance = new Api.TrainingPlansItemsItemIdOverridePostRequest();
      //expect(instance).to.be();
    });

    it('should have the property customNotes (base name: "custom_notes")', function() {
      // uncomment below and update the code to test the property customNotes
      //var instance = new Api.TrainingPlansItemsItemIdOverridePostRequest();
      //expect(instance).to.be();
    });

  });

}));
