/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AthleteProfileRequest from '../models/AthleteProfileRequest';
import AthleteProfileResponse from '../models/AthleteProfileResponse';
import AthleteRegisterRequest from '../models/AthleteRegisterRequest';
import AthleteTeamResponse from '../models/AthleteTeamResponse';
import AuthChangePasswordPostRequest from '../models/AuthChangePasswordPostRequest';
import ErrorResponse from '../models/ErrorResponse';
import InviteAllResponse from '../models/InviteAllResponse';
import InviteCancelRequest from '../models/InviteCancelRequest';
import InviteCreateRequest from '../models/InviteCreateRequest';
import InviteCreateResponse from '../models/InviteCreateResponse';
import InviteDetailsRequest from '../models/InviteDetailsRequest';
import InviteDetailsResponse from '../models/InviteDetailsResponse';
import InviteRegisterRequest from '../models/InviteRegisterRequest';
import LoginRequest from '../models/LoginRequest';
import LoginResponse from '../models/LoginResponse';

/**
* Auth service.
* @module api/AuthApi
* @version 1.0.0
*/
export default class AuthApi {

    /**
    * Constructs a new AuthApi. 
    * @alias module:api/AuthApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the authAthleteProfilePost operation.
     * @callback module:api/AuthApi~authAthleteProfilePostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/AthleteProfileResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Профиль спортсмена
     * @param {module:models/AthleteProfileRequest} athleteProfileRequest 
     * @param {module:api/AuthApi~authAthleteProfilePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/AthleteProfileResponse}
     */
    authAthleteProfilePost(athleteProfileRequest, callback) {
      let postBody = athleteProfileRequest;
      // verify the required parameter 'athleteProfileRequest' is set
      if (athleteProfileRequest === undefined || athleteProfileRequest === null) {
        throw new Error("Missing the required parameter 'athleteProfileRequest' when calling authAthleteProfilePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AthleteProfileResponse;
      return this.apiClient.callApi(
        '/auth/athlete-profile', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authAthleteTeamPost operation.
     * @callback module:api/AuthApi~authAthleteTeamPostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/AthleteTeamResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Команда спортсмена
     * @param {module:models/AthleteProfileRequest} athleteProfileRequest 
     * @param {module:api/AuthApi~authAthleteTeamPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/AthleteTeamResponse}
     */
    authAthleteTeamPost(athleteProfileRequest, callback) {
      let postBody = athleteProfileRequest;
      // verify the required parameter 'athleteProfileRequest' is set
      if (athleteProfileRequest === undefined || athleteProfileRequest === null) {
        throw new Error("Missing the required parameter 'athleteProfileRequest' when calling authAthleteTeamPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AthleteTeamResponse;
      return this.apiClient.callApi(
        '/auth/athlete-team', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authCancelInvitePost operation.
     * @callback module:api/AuthApi~authCancelInvitePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Отмена инвайта
     * @param {module:models/InviteCancelRequest} inviteCancelRequest 
     * @param {module:api/AuthApi~authCancelInvitePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    authCancelInvitePost(inviteCancelRequest, callback) {
      let postBody = inviteCancelRequest;
      // verify the required parameter 'inviteCancelRequest' is set
      if (inviteCancelRequest === undefined || inviteCancelRequest === null) {
        throw new Error("Missing the required parameter 'inviteCancelRequest' when calling authCancelInvitePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/auth/cancel-invite', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authChangePasswordPost operation.
     * @callback module:api/AuthApi~authChangePasswordPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Смена пароля пользователя
     * @param {module:models/AuthChangePasswordPostRequest} authChangePasswordPostRequest 
     * @param {module:api/AuthApi~authChangePasswordPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    authChangePasswordPost(authChangePasswordPostRequest, callback) {
      let postBody = authChangePasswordPostRequest;
      // verify the required parameter 'authChangePasswordPostRequest' is set
      if (authChangePasswordPostRequest === undefined || authChangePasswordPostRequest === null) {
        throw new Error("Missing the required parameter 'authChangePasswordPostRequest' when calling authChangePasswordPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/auth/change-password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authCreateInviteCodePost operation.
     * @callback module:api/AuthApi~authCreateInviteCodePostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/InviteCreateResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создание инвайта для врача или тренера
     * @param {module:models/InviteCreateRequest} inviteCreateRequest 
     * @param {module:api/AuthApi~authCreateInviteCodePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/InviteCreateResponse}
     */
    authCreateInviteCodePost(inviteCreateRequest, callback) {
      let postBody = inviteCreateRequest;
      // verify the required parameter 'inviteCreateRequest' is set
      if (inviteCreateRequest === undefined || inviteCreateRequest === null) {
        throw new Error("Missing the required parameter 'inviteCreateRequest' when calling authCreateInviteCodePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InviteCreateResponse;
      return this.apiClient.callApi(
        '/auth/create-invite-code', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authGetAllInvitesGet operation.
     * @callback module:api/AuthApi~authGetAllInvitesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/InviteAllResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Все инвайты
     * @param {module:api/AuthApi~authGetAllInvitesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/InviteAllResponse}
     */
    authGetAllInvitesGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InviteAllResponse;
      return this.apiClient.callApi(
        '/auth/get-all-invites', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authGetInviteDetailsPost operation.
     * @callback module:api/AuthApi~authGetInviteDetailsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/InviteDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Информация о приглашении
     * @param {module:models/InviteDetailsRequest} inviteDetailsRequest 
     * @param {module:api/AuthApi~authGetInviteDetailsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/InviteDetailsResponse}
     */
    authGetInviteDetailsPost(inviteDetailsRequest, callback) {
      let postBody = inviteDetailsRequest;
      // verify the required parameter 'inviteDetailsRequest' is set
      if (inviteDetailsRequest === undefined || inviteDetailsRequest === null) {
        throw new Error("Missing the required parameter 'inviteDetailsRequest' when calling authGetInviteDetailsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InviteDetailsResponse;
      return this.apiClient.callApi(
        '/auth/get-invite-details', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authLoginPost operation.
     * @callback module:api/AuthApi~authLoginPostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/LoginResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Авторизация
     * @param {module:models/LoginRequest} loginRequest 
     * @param {module:api/AuthApi~authLoginPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/LoginResponse}
     */
    authLoginPost(loginRequest, callback) {
      let postBody = loginRequest;
      // verify the required parameter 'loginRequest' is set
      if (loginRequest === undefined || loginRequest === null) {
        throw new Error("Missing the required parameter 'loginRequest' when calling authLoginPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LoginResponse;
      return this.apiClient.callApi(
        '/auth/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authRegisterAthletePost operation.
     * @callback module:api/AuthApi~authRegisterAthletePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Регистрация спортсмена
     * @param {module:models/AthleteRegisterRequest} athleteRegisterRequest 
     * @param {module:api/AuthApi~authRegisterAthletePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    authRegisterAthletePost(athleteRegisterRequest, callback) {
      let postBody = athleteRegisterRequest;
      // verify the required parameter 'athleteRegisterRequest' is set
      if (athleteRegisterRequest === undefined || athleteRegisterRequest === null) {
        throw new Error("Missing the required parameter 'athleteRegisterRequest' when calling authRegisterAthletePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/auth/register/athlete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authRegisterInvitePost operation.
     * @callback module:api/AuthApi~authRegisterInvitePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Регистрация по инвайт-коду (для тренеров и врачей)
     * @param {module:models/InviteRegisterRequest} inviteRegisterRequest 
     * @param {module:api/AuthApi~authRegisterInvitePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    authRegisterInvitePost(inviteRegisterRequest, callback) {
      let postBody = inviteRegisterRequest;
      // verify the required parameter 'inviteRegisterRequest' is set
      if (inviteRegisterRequest === undefined || inviteRegisterRequest === null) {
        throw new Error("Missing the required parameter 'inviteRegisterRequest' when calling authRegisterInvitePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/auth/register/invite', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
