/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BiometricInput from '../models/BiometricInput';
import ErrorResponse from '../models/ErrorResponse';

/**
* Biometrics service.
* @module api/BiometricsApi
* @version 1.0.0
*/
export default class BiometricsApi {

    /**
    * Constructs a new BiometricsApi. 
    * @alias module:api/BiometricsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the biometricsPost operation.
     * @callback module:api/BiometricsApi~biometricsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Ввод биометрических данных спортсменом
     * @param {module:models/BiometricInput} biometricInput 
     * @param {module:api/BiometricsApi~biometricsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    biometricsPost(biometricInput, callback) {
      let postBody = biometricInput;
      // verify the required parameter 'biometricInput' is set
      if (biometricInput === undefined || biometricInput === null) {
        throw new Error("Missing the required parameter 'biometricInput' when calling biometricsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/biometrics', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
