/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AllAthletesResponse from '../models/AllAthletesResponse';
import AthleteProfileRequest from '../models/AthleteProfileRequest';
import ErrorResponse from '../models/ErrorResponse';
import TeamAthleteStatusResponse from '../models/TeamAthleteStatusResponse';
import TeamCreateRequest from '../models/TeamCreateRequest';
import TeamGetAthletesResponse from '../models/TeamGetAthletesResponse';
import TeamGetCoachesResponse from '../models/TeamGetCoachesResponse';
import TeamJoinRequest from '../models/TeamJoinRequest';
import TeamJoinsListResponse from '../models/TeamJoinsListResponse';
import TeamRequest from '../models/TeamRequest';
import TeamResponse from '../models/TeamResponse';

/**
* Teams service.
* @module api/TeamsApi
* @version 1.0.0
*/
export default class TeamsApi {

    /**
    * Constructs a new TeamsApi. 
    * @alias module:api/TeamsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the teamAthleteRemovePost operation.
     * @callback module:api/TeamsApi~teamAthleteRemovePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Удаление спортсмена из команды
     * @param {module:models/AthleteProfileRequest} athleteProfileRequest 
     * @param {module:api/TeamsApi~teamAthleteRemovePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamAthleteRemovePost(athleteProfileRequest, callback) {
      let postBody = athleteProfileRequest;
      // verify the required parameter 'athleteProfileRequest' is set
      if (athleteProfileRequest === undefined || athleteProfileRequest === null) {
        throw new Error("Missing the required parameter 'athleteProfileRequest' when calling teamAthleteRemovePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/team/athlete-remove', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamAthleteTeamStatusGet operation.
     * @callback module:api/TeamsApi~teamAthleteTeamStatusGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TeamAthleteStatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Заявка на вступление в команду
     * @param {module:api/TeamsApi~teamAthleteTeamStatusGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TeamAthleteStatusResponse}
     */
    teamAthleteTeamStatusGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamAthleteStatusResponse;
      return this.apiClient.callApi(
        '/team/athlete-team-status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsAllAthletesGet operation.
     * @callback module:api/TeamsApi~teamsAllAthletesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/AllAthletesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список всех спортсменов
     * @param {module:api/TeamsApi~teamsAllAthletesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/AllAthletesResponse}
     */
    teamsAllAthletesGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AllAthletesResponse;
      return this.apiClient.callApi(
        '/teams/all-athletes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsAthletesPost operation.
     * @callback module:api/TeamsApi~teamsAthletesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TeamGetAthletesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список спортсменов в команде
     * @param {module:models/TeamRequest} teamRequest 
     * @param {module:api/TeamsApi~teamsAthletesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TeamGetAthletesResponse}
     */
    teamsAthletesPost(teamRequest, callback) {
      let postBody = teamRequest;
      // verify the required parameter 'teamRequest' is set
      if (teamRequest === undefined || teamRequest === null) {
        throw new Error("Missing the required parameter 'teamRequest' when calling teamsAthletesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TeamGetAthletesResponse;
      return this.apiClient.callApi(
        '/teams/athletes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsCoachesPost operation.
     * @callback module:api/TeamsApi~teamsCoachesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TeamGetCoachesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список тренеров в команде
     * @param {module:models/TeamRequest} teamRequest 
     * @param {module:api/TeamsApi~teamsCoachesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TeamGetCoachesResponse}
     */
    teamsCoachesPost(teamRequest, callback) {
      let postBody = teamRequest;
      // verify the required parameter 'teamRequest' is set
      if (teamRequest === undefined || teamRequest === null) {
        throw new Error("Missing the required parameter 'teamRequest' when calling teamsCoachesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TeamGetCoachesResponse;
      return this.apiClient.callApi(
        '/teams/coaches', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsCreatePost operation.
     * @callback module:api/TeamsApi~teamsCreatePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создание команды
     * @param {module:models/TeamCreateRequest} teamCreateRequest 
     * @param {module:api/TeamsApi~teamsCreatePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsCreatePost(teamCreateRequest, callback) {
      let postBody = teamCreateRequest;
      // verify the required parameter 'teamCreateRequest' is set
      if (teamCreateRequest === undefined || teamCreateRequest === null) {
        throw new Error("Missing the required parameter 'teamCreateRequest' when calling teamsCreatePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsGet operation.
     * @callback module:api/TeamsApi~teamsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TeamResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список команд
     * @param {module:api/TeamsApi~teamsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TeamResponse}
     */
    teamsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamResponse;
      return this.apiClient.callApi(
        '/teams', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinPost operation.
     * @callback module:api/TeamsApi~teamsJoinPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Запрос спортсмена на вступление в команду
     * @param {module:models/TeamJoinRequest} teamJoinRequest 
     * @param {module:api/TeamsApi~teamsJoinPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsJoinPost(teamJoinRequest, callback) {
      let postBody = teamJoinRequest;
      // verify the required parameter 'teamJoinRequest' is set
      if (teamJoinRequest === undefined || teamJoinRequest === null) {
        throw new Error("Missing the required parameter 'teamJoinRequest' when calling teamsJoinPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/join', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinRequestIdApprovePost operation.
     * @callback module:api/TeamsApi~teamsJoinRequestIdApprovePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Одобрение заявки на вступление в команду
     * @param {Number} requestId 
     * @param {module:api/TeamsApi~teamsJoinRequestIdApprovePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsJoinRequestIdApprovePost(requestId, callback) {
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling teamsJoinRequestIdApprovePost");
      }

      let pathParams = {
        'request_id': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/join/{request_id}/approve', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinRequestIdRejectPost operation.
     * @callback module:api/TeamsApi~teamsJoinRequestIdRejectPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Отклонение заявки на вступление в команду
     * @param {Number} requestId 
     * @param {module:api/TeamsApi~teamsJoinRequestIdRejectPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsJoinRequestIdRejectPost(requestId, callback) {
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling teamsJoinRequestIdRejectPost");
      }

      let pathParams = {
        'request_id': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/join/{request_id}/reject', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinsListGet operation.
     * @callback module:api/TeamsApi~teamsJoinsListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TeamJoinsListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список заявок на вступление в команды
     * @param {module:api/TeamsApi~teamsJoinsListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TeamJoinsListResponse}
     */
    teamsJoinsListGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamJoinsListResponse;
      return this.apiClient.callApi(
        '/teams/joins-list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinsListTeamIdGet operation.
     * @callback module:api/TeamsApi~teamsJoinsListTeamIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/TeamJoinsListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список заявок на вступление в команду
     * @param {Number} teamId 
     * @param {module:api/TeamsApi~teamsJoinsListTeamIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/TeamJoinsListResponse}
     */
    teamsJoinsListTeamIdGet(teamId, callback) {
      let postBody = null;
      // verify the required parameter 'teamId' is set
      if (teamId === undefined || teamId === null) {
        throw new Error("Missing the required parameter 'teamId' when calling teamsJoinsListTeamIdGet");
      }

      let pathParams = {
        'team_id': teamId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamJoinsListResponse;
      return this.apiClient.callApi(
        '/teams/joins-list/{team_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
