/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../models/ErrorResponse';
import TeamsJoinPostRequest from '../models/TeamsJoinPostRequest';

/**
* Teams service.
* @module api/TeamsApi
* @version 1.0.0
*/
export default class TeamsApi {

    /**
    * Constructs a new TeamsApi. 
    * @alias module:api/TeamsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the teamsJoinPost operation.
     * @callback module:api/TeamsApi~teamsJoinPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Запрос спортсмена на вступление в команду
     * @param {module:models/TeamsJoinPostRequest} teamsJoinPostRequest 
     * @param {module:api/TeamsApi~teamsJoinPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsJoinPost(teamsJoinPostRequest, callback) {
      let postBody = teamsJoinPostRequest;
      // verify the required parameter 'teamsJoinPostRequest' is set
      if (teamsJoinPostRequest === undefined || teamsJoinPostRequest === null) {
        throw new Error("Missing the required parameter 'teamsJoinPostRequest' when calling teamsJoinPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/join', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinRequestIdApprovePost operation.
     * @callback module:api/TeamsApi~teamsJoinRequestIdApprovePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Одобрение заявки на вступление в команду
     * @param {Number} requestId 
     * @param {module:api/TeamsApi~teamsJoinRequestIdApprovePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsJoinRequestIdApprovePost(requestId, callback) {
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling teamsJoinRequestIdApprovePost");
      }

      let pathParams = {
        'request_id': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/join/{request_id}/approve', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the teamsJoinRequestIdRejectPost operation.
     * @callback module:api/TeamsApi~teamsJoinRequestIdRejectPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Отклонение заявки на вступление в команду
     * @param {Number} requestId 
     * @param {module:api/TeamsApi~teamsJoinRequestIdRejectPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamsJoinRequestIdRejectPost(requestId, callback) {
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling teamsJoinRequestIdRejectPost");
      }

      let pathParams = {
        'request_id': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams/join/{request_id}/reject', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
