/**
 * Спортивная система | API
 * Система для регистрации, авторизации и управления ролями пользователей. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TrainingPlansItemsItemIdOverridePostRequest from '../models/TrainingPlansItemsItemIdOverridePostRequest';
import TrainingPlansPlanIdAssignPostRequest from '../models/TrainingPlansPlanIdAssignPostRequest';
import TrainingPlansPlanIdItemsPostRequest from '../models/TrainingPlansPlanIdItemsPostRequest';
import TrainingPlansPostRequest from '../models/TrainingPlansPostRequest';

/**
* Training service.
* @module api/TrainingApi
* @version 1.0.0
*/
export default class TrainingApi {

    /**
    * Constructs a new TrainingApi. 
    * @alias module:api/TrainingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the trainingPlansItemsItemIdDelete operation.
     * @callback module:api/TrainingApi~trainingPlansItemsItemIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Удаление пункта плана
     * @param {Number} itemId 
     * @param {module:api/TrainingApi~trainingPlansItemsItemIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    trainingPlansItemsItemIdDelete(itemId, callback) {
      let postBody = null;
      // verify the required parameter 'itemId' is set
      if (itemId === undefined || itemId === null) {
        throw new Error("Missing the required parameter 'itemId' when calling trainingPlansItemsItemIdDelete");
      }

      let pathParams = {
        'item_id': itemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/training-plans/items/{item_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingPlansItemsItemIdOverridePost operation.
     * @callback module:api/TrainingApi~trainingPlansItemsItemIdOverridePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Изменение пункта плана для конкретного спортсмена
     * @param {Number} itemId 
     * @param {module:models/TrainingPlansItemsItemIdOverridePostRequest} trainingPlansItemsItemIdOverridePostRequest 
     * @param {module:api/TrainingApi~trainingPlansItemsItemIdOverridePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    trainingPlansItemsItemIdOverridePost(itemId, trainingPlansItemsItemIdOverridePostRequest, callback) {
      let postBody = trainingPlansItemsItemIdOverridePostRequest;
      // verify the required parameter 'itemId' is set
      if (itemId === undefined || itemId === null) {
        throw new Error("Missing the required parameter 'itemId' when calling trainingPlansItemsItemIdOverridePost");
      }
      // verify the required parameter 'trainingPlansItemsItemIdOverridePostRequest' is set
      if (trainingPlansItemsItemIdOverridePostRequest === undefined || trainingPlansItemsItemIdOverridePostRequest === null) {
        throw new Error("Missing the required parameter 'trainingPlansItemsItemIdOverridePostRequest' when calling trainingPlansItemsItemIdOverridePost");
      }

      let pathParams = {
        'item_id': itemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/training-plans/items/{item_id}/override', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingPlansPlanIdAssignPost operation.
     * @callback module:api/TrainingApi~trainingPlansPlanIdAssignPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Назначить план спортсменам
     * @param {Number} planId 
     * @param {module:models/TrainingPlansPlanIdAssignPostRequest} trainingPlansPlanIdAssignPostRequest 
     * @param {module:api/TrainingApi~trainingPlansPlanIdAssignPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    trainingPlansPlanIdAssignPost(planId, trainingPlansPlanIdAssignPostRequest, callback) {
      let postBody = trainingPlansPlanIdAssignPostRequest;
      // verify the required parameter 'planId' is set
      if (planId === undefined || planId === null) {
        throw new Error("Missing the required parameter 'planId' when calling trainingPlansPlanIdAssignPost");
      }
      // verify the required parameter 'trainingPlansPlanIdAssignPostRequest' is set
      if (trainingPlansPlanIdAssignPostRequest === undefined || trainingPlansPlanIdAssignPostRequest === null) {
        throw new Error("Missing the required parameter 'trainingPlansPlanIdAssignPostRequest' when calling trainingPlansPlanIdAssignPost");
      }

      let pathParams = {
        'plan_id': planId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/training-plans/{plan_id}/assign', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingPlansPlanIdItemsPost operation.
     * @callback module:api/TrainingApi~trainingPlansPlanIdItemsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Добавление пункта в план
     * @param {Number} planId 
     * @param {module:models/TrainingPlansPlanIdItemsPostRequest} trainingPlansPlanIdItemsPostRequest 
     * @param {module:api/TrainingApi~trainingPlansPlanIdItemsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    trainingPlansPlanIdItemsPost(planId, trainingPlansPlanIdItemsPostRequest, callback) {
      let postBody = trainingPlansPlanIdItemsPostRequest;
      // verify the required parameter 'planId' is set
      if (planId === undefined || planId === null) {
        throw new Error("Missing the required parameter 'planId' when calling trainingPlansPlanIdItemsPost");
      }
      // verify the required parameter 'trainingPlansPlanIdItemsPostRequest' is set
      if (trainingPlansPlanIdItemsPostRequest === undefined || trainingPlansPlanIdItemsPostRequest === null) {
        throw new Error("Missing the required parameter 'trainingPlansPlanIdItemsPostRequest' when calling trainingPlansPlanIdItemsPost");
      }

      let pathParams = {
        'plan_id': planId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/training-plans/{plan_id}/items', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingPlansPost operation.
     * @callback module:api/TrainingApi~trainingPlansPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создание тренировочного плана
     * @param {module:models/TrainingPlansPostRequest} trainingPlansPostRequest 
     * @param {module:api/TrainingApi~trainingPlansPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    trainingPlansPost(trainingPlansPostRequest, callback) {
      let postBody = trainingPlansPostRequest;
      // verify the required parameter 'trainingPlansPostRequest' is set
      if (trainingPlansPostRequest === undefined || trainingPlansPostRequest === null) {
        throw new Error("Missing the required parameter 'trainingPlansPostRequest' when calling trainingPlansPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/training-plans', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
